### ISSUE TITLE
Sub-expression in if block no longer works

### ISSUE THREAD

**Issue by amaclean** [rexm/Handlebars.Net#100]
Hey Rex,

It seems that the [fix](https://github.com/rexm/Handlebars.Net/commit/3e5e09666c660ff61745d87b08277992ffe15822) for issue #79 (chained conditionals) has broken support for using a sub-expression with the if block helper.

`{{#if (isEqual arg1 arg2)}}True{{/if}}`

This now throws a _sub-expression does not contain a converted MethodCall expression_ exception.

 

I've added a new test that passes before this commit and fails afterwards [here](https://github.com/amaclean/Handlebars.Net/commit/596fbe22ac454f705db6cecb3e7d299fd0e89d53).

I'm happy to check this out when I get some time, but I thought I'd let you know as well.

**Comment by rexm** [comment]
Updated NuGet 1.6.3, thanks for reporting and for the test case!
