### ISSUE TITLE
Is it possible to get compatibility with Windows Universal 10?

### ISSUE THREAD

**Issue by jcarruo** [rexm/Handlebars.Net#102]

**Comment by rexm** [comment]
My understanding is that PCLs can be used with .NET for UWP, but I haven't worked with UWP myself so that may be wrong. It would be helpful to know what's missing to make it UWP compatible.

**Comment by jcarruo** [comment]
To start out I simply created a UWP project and tried to pull down the handlebars.net nuget package;  this fails with a very generic message saying handlebars.net is incompatible. 

I pulled down the zipped source and noticed windows universal 10 wasn't targeted for the portable project. I flicked this over to specifically target it and the root cause became apparent. All the reflection bits and pieces change when targeting this platform, I'm assuming this caused the incompatability issues  when trying add the nuget package.

Calls like Delegate.CreateDelegate and the Method property aren't available.  I refactored and managed to get it building but unit tests failed.  For some reason, BiltInHelpers doesn't return the correct set of helpers;  test like BasicWith fail as the "#with" helper cant be found.  I would say my factoring was incorrect, but you might have better luck than me as you know the code intimately!

-----Original Message-----

**Comment by rexm** [comment]
How did you refactor to remove the reflection?

**Comment by jcarruo** [comment]
Sorry wrong choice of words.  I just attempted to fix the build errors.  I think I’ve broken its back (a good thing – aussie slang).

All unit tests now pass except DeepIf.  The following line/s fail:
`Assert.AreEqual(Environment.NewLine + "a is true" + Environment.NewLine, resultTrueTrue);`

Environment.NewLine = “\r\n” so the test is:
`"\r\na is true\r\n" == "\na is true\n"`

Are you really expecting “\r” in the value resultTrueTrue?  

These tests don’t happen to executed on LINUX/Mono do they?

Have you got another email address I can attach and send the solution to?

Cheers

**Comment by rexm** [comment]
The most helpful thing would be to fork the repo to your own GH account, push your changes there, and link to them so we can do a diff, and PR back into the main repo.

**Comment by jcarruo** [comment]
Done mate

**Comment by rexm** [comment]
Thanks, I'll take a look.

**Comment by rexm** [comment]
We now have full net46/mono and netcore support.
