### ISSUE TITLE
How would you use a helper with parameters?

### ISSUE THREAD

**Issue by markalanevans** [rexm/Handlebars.Net#103]
For example a more generic href helper.

{{#href url text}}

**Comment by rexm** [comment]
I am not sure what you mean by "use a helper" in this context. Can you share some more details on what you are trying to do and where you're getting stuck?

**Comment by markalanevans** [comment]
Sorry, was looking for an example of creating a helper with parameters.

In your example
```
Handlebars.RegisterHelper("link_to", (writer, context, parameters) => {
  writer.WriteSafeString("<a href='" + context.url + "'>" + context.text + "</a>");
});
```

You use context. I'd rather not use the context and assume variable names. Rather, i'd like to just pass in the url and the url_text.

Perhaps an example would be

```
Checkout the profile for   {{#link_to  customerUrl customerName }}.
```

Just wondering how to reference params in c# when defining the helper.

**Comment by rexm** [comment]
The last argument of the helper method is an object array. That will contain the values of the parameters.

**Comment by rexm** [comment]
OK to close?

**Comment by markalanevans** [comment]
Got it. Tnx
