### ISSUE TITLE
Don't work with JObject

### ISSUE THREAD

**Issue by victorsoliveira** [rexm/Handlebars.Net#110]
Hi, i'm trying to compile a handlebars template with a JObject deserialized source from JSON string and some block built-in helpers don't work like IF, WITH, EACH...

Look at an example that i wrote below:

`

            var text = "{  \"ChangedProperties\": {\n    \"End\": {\n      \"PreviousValue\": \"2015-11-02T00:00:00\",\n      \"ActualValue\": \"2015-11-03T00:00:00\"\n    }\n  }\n}";
            var source = JsonConvert.DeserializeObject(text);

            var templateText =
                "<!DOCTYPE html><html><head></head><body>{{#if ChangedProperties.End.PreviousValue}}<span>{{ChangedProperties.End.PreviousValue}}</span>{{/if}}<br/>{{#if ChangedProperties.End.ActualValue}}<span>{{ChangedProperties.End.ActualValue}}</span>{{/if}}</body></html>";

            var template = Handlebars.Compile(templateText);

            var result = template(text);

            //Result:
            //<!DOCTYPE html><html><head></head><body><br/></body></html>

`

**Comment by victorsoliveira** [comment]
Have you ever fix that ?

**Comment by rexm** [comment]
Handlebars.Net does not natively understand JObjects. Search through the closed issues and you'll see plenty of references and examples to write your code in a way that isn't tightly coupled to JSON.NET.

**Comment by PaulBullivant** [comment]
Try using the C# ExpandoObject instead.  Handlebars.Net deals with this better than JObject

var source = JsonConvert.DeserializeObject<ExpandoObject>(text);
var template = Handlebars.Compile(templateText);
var result = template(text);

**Comment by victorsoliveira** [comment]
Thanks @PaulBullivant ! 
I already had discovered this. Rs
