### ISSUE TITLE
Custom tag delimiter does not work.

### ISSUE THREAD

**Issue by HoangDang2016** [rexm/Handlebars.Net#111]
Is it allowed in Handlebars.net to change delimiters like Mustache template?

* {{default_tags}}
{{=<% %>=}}
* <% erb_style_tags %>
<%={{ }}=%>
* {{ default_tags_again }}

**Comment by rexm** [comment]
This isn't supported by the original JS handlebars library, nor this .NET implementation. It's not impossible, but would make the lexer significantly more complicated.

**Comment by HoangDang2016** [comment]
Thank you for the answer. There are so much overlapping between Handlebars and Mustache that caused my confusion.
