### ISSUE TITLE
Strange dictionary behaviors.

### ISSUE THREAD

**Issue by HoangDang2016** [rexm/Handlebars.Net#112]
string source = @"{{#ADictionary}}<b>{{key}},{{value}}</b>{{/ADictionary}}";
var template = Handlebars.Compile(source);
var result = template(new 
            {
                ADictionary = new Dictionary<string, int>
                    {
                        { "key5", 14 },
                        { "key6", 15 },
                        { "key7", 16 },
                        { "key8", 17 }
                    }
            });
Console.WriteLine(result);

This will produce <b>,</b> for each row of dict data.

string source = @"{{#ADictionary}}<b>{{@key}},{{@value}}</b>{{/ADictionary}}";
var template = Handlebars.Compile(source);
var result = template(new 
            {
                ADictionary = new Dictionary<string, int>
                    {
                        { "key5", 14 },
                        { "key6", 15 },
                        { "key7", 16 },
                        { "key8", 17 }
                    }
            });
Console.WriteLine(result);

This will produce
<b>key5, [key5, 14]</b>
<b>key6, [key6, 15]</b>
<b>key7, [key7, 16]</b>
<b>key8, [key8, 17]</b>

I'm expecting <b>key5,14</b> and so on for each row with its key value pairs.

**Comment by rexm** [comment]
Couple things happening here:
- For some reason the member resolution in a dictionary iterator is case-sensitive, so if you use `Key` and `Value` it will work.
- `@value` is an alias for `this`, which is the entire object in the current context. For a dictionary, that is the `KeyValuePair<K,V>` - which the stringified version is "[{key}, {value}]"

Two things we probably want to consider, but need to think through all the implications first:
- In a dictionary iterator context, should `@value` take a special, different meaning to only be the value part of the KVP?
- Why is member resolution in a dictionary case-sensitive, and would it break anything to make it case-insensitive?

**Comment by HoangDang2016** [comment]
I would leave everything as it is.  It makes more sense after your explanation.

**Comment by rexm** [comment]
Version 1.6.5 is out; removes case-sensitivity for member resolution.
