### ISSUE TITLE
Sub-expression must be the final parameter to a helper

### ISSUE THREAD

**Issue by kit299** [rexm/Handlebars.Net#115]
Sub-expressions are only supported as the final parameter to a helper.

Assume I have a helper "write" that simply outputs its arguments and a helper "add" that returns the sum of its arguments.

It is impossible to do this: `{{write (add 1 2) (add 3 4)}}`   (Expected output: `3 7`)

This works: `{{write "hello" (add 1 2)}}` (Outputs: `hello 3`)
But this does not: `{{write (add 1 2) "hello"}}` (Expected: `3 hello` but throws exception during compile)

Here's an example unit test, based on the existing test "BasicSubExpressionWithNumericLiteralArguments"

```
	[Test]
		public void TwoBasicSubExpressionsWithNumericLiteralArguments()
		{
			var helperName = "helper-" + Guid.NewGuid().ToString(); //randomize helper name
			var subHelperName = "subhelper-" + Guid.NewGuid().ToString(); //randomize helper name
			Handlebars.RegisterHelper(helperName, (writer, context, args) => {
				writer.Write("Math " + args[0] + " " + args[1]);
			});

			Handlebars.RegisterHelper(subHelperName, (writer, context, args) => {
				args = args.Select(a => (object)int.Parse((string)a)).ToArray();
				writer.Write((int)args[0] + (int)args[1]);
			});

			var source = "{{" + helperName + " (" + subHelperName + " 1 2) (" + subHelperName + " 3 4)}}";

			var template = Handlebars.Compile(source);

			var output = template(new { });

			var expected = "Math 3 7";

			Assert.AreEqual(expected, output);
		}
```

Which actually throws this exception when compiling:

```
Token '}}' could not be converted to an expression

   at HandlebarsDotNet.Compiler.SubExpressionConverter.AccumulateSubExpression(IEnumerator`1 enumerator)
   at HandlebarsDotNet.Compiler.SubExpressionConverter.BuildSubExpression(IEnumerator`1 enumerator)
   at HandlebarsDotNet.Compiler.SubExpressionConverter.<ConvertTokens>c__Iterator0.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HandlebarsDotNet.Compiler.ExpressionBuilder.ConvertTokensToExpressions(IEnumerable`1 tokens)
   at HandlebarsDotNet.Compiler.HandlebarsCompiler.Compile(TextReader source)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template)
```

**Comment by kit299** [comment]
I should probably point out that what I'm really trying to do is nest sub-expressions, e.g. `{{write (add (add 1 2) 3)}}` expected output: `6`

But while trying to get this working I also noticed the above issue, that the sub-expression must come last.

**Comment by rexm** [comment]
Your nested sub-expression scenario does indeed fail, but the other test cases you provided all pass for me:

- `{{write (add 1 2) (add 3 4)}}`
- `{{write (add 1 2) "hello"}}`

Can you provide some details about what version & platform you are using and confirm that is the exact template & test case which fails?

**Comment by rexm** [comment]
I've released 1.6.7 which supports nested sub-expressions.

**Comment by kit299** [comment]
Thanks for the quick response. I was testing with 1.6.0 when I encountered the error above (probably should have mentioned that..)

I've updated to 1.6.7 and the error no longer occurs - thanks!

**Comment by rexm** [comment]
Prior to version 1.6.2 sub-expression support was not very robust, so that explains it. Glad you got it working.
