### ISSUE TITLE
azure worker role - nothing gets done to my template

### ISSUE THREAD

**Issue by WilliamHBonney** [rexm/Handlebars.Net#117]
My app works fine when i run it locally.  When i deploy it to azure no exceptions occur at runtime, but the result string is purely my template. With no processing done at all.

Local 
"hello david you are an adult"

Azure
"hello {{Model.name}} {{#If Model.Adult}} you are an adult {{/if}}"

Has anyone experienced this? Because i dont get any exceptions i am unsure where to look.  Could it be a .net dependency/vc++ redistributable/execute permissions/file share?

Thanks

**Comment by rexm** [comment]
Why did you mention vc++? Is that a factor in your app?

**Comment by WilliamHBonney** [comment]
No. But I thought there might be some dependency I was unaware of

**Comment by WilliamHBonney** [comment]
A

**Comment by rexm** [comment]
Glad you got it sorted!
