### ISSUE TITLE
RegisterHelper with title "json" results in "Reached end of template..." error

### ISSUE THREAD

**Issue by alittlerabbi** [rexm/Handlebars.Net#118]
With the following template and helper,
```html
<div>
{{json AnyDataFromContext}}
</div>
```
```javascript
Handlebars.RegisterHelper("json", ( writer, context, arguments ) =>
{
	writer.Write("This will functionally break.");
});
```
the response will end in with the error: "Reached end of template before block expression was closed"

However, if i change _both_ into the following (notice that the helper is no longer titled "**json**")
```html
<div>
{{jsonXYZ AnyDataFromContext}}
</div>
```
```javascript
Handlebars.RegisterHelper("jsonXYZ", ( writer, context, arguments ) =>
{
	writer.Write("This functionally works.");
});
```
the result is
```html
<div>
This functionally works.
</div>
```

**Comment by rexm** [comment]
I set up the test scenario you described above and it works for me as expected. Can you confirm the following so we can better troubleshoot:

- Is this is the exact template and helper you're using?
- What version of Handlebars.Net are you using?
- What platform/OS are you using?

**Comment by alittlerabbi** [comment]
Cannot replicate the issue anymore. Closing this issue.

**Comment by StefH** [comment]
An old issue, but I did have the same problem with a helper named "Math.Add".

Using Windows10, .NET Framework 4.5.1 and Handlebars.Net version 1.9.0.
