### ISSUE TITLE
Option to disable HTML encoding of values

### ISSUE THREAD

**Issue by imsedim** [rexm/Handlebars.Net#119]
Even though Handlebars is mainly used for producing HTML templates, it's a great tool that could be used for generating any other types of content. 

With Handlebars.Net there is a caveat though - HTML escape is always used (unless explicitly turned off in the template or helper), meaning that any non-HTML template would have a lot of unnecessary noise ({{{...}}} or custom helpers) to alleviate this (one of the reasons why it matters is that  `EncodedTextWriter `is a bit too strict and encodes everything above char 159, compared to Handlebars.js that only encodes symbols &<>"'`=)

The handlebars.js has an option `noEscape` which is helpful in exactly this situation.

So this issue is basically a feature request to include this `noEscape` capability in the Handlebars.Net either in the form of configuration option or as an extension point for custom-written `TextWriter`

**Comment by imsedim** [comment]
The customizable TextWriter seems to be relatively straight forward fix, so if there are no objections on your side, I can make a PR

**Comment by Breate** [comment]
Can you provide a solution to fix encoding cause i have a same issue.

**Comment by rexm** [comment]
Sure, there is a configuration object hook we've discussed turning into an options hash that works like the one in the JS library. And passing a standard text writer through the chain shouldn't be too hard. Look forward to the PR

**Comment by imsedim** [comment]
Posted the PR

**Comment by rexm** [comment]
Fixed in #120

**Comment by imsedim** [comment]
Example of how to turn off the encoding:

`var configuration = new HandlebarsConfiguration { TextEncoder = null };`
