### ISSUE TITLE
Load testing problems

### ISSUE THREAD

**Issue by nkwinder** [rexm/Handlebars.Net#12]
I've completed a full page of an eshop, rendered using this library. During development and testing everything seems to be working just as expected and really fast. 
As a last step before going to production, i have performed some load tests in this page, and the results revealed some issues:

1. The load test lasts 5 minutes. A total of 1000 requests are made. From these, the 150 (average) requests have failed, all with the same 2 errors (attached screenshots).
![loadtesthandlebarserror1](https://cloud.githubusercontent.com/assets/1158542/5593437/ba666eb8-9217-11e4-8840-6a71c0ad9a4d.JPG)
![loadtesthandlebarserror2](https://cloud.githubusercontent.com/assets/1158542/5593439/c2480d58-9217-11e4-99ab-b537c4fe695c.JPG)

2. When the load test starts, the process memory is at around 500mb. After the test, the memory is at around 3-7 GB!! (3gb if i use registerTemplate only on app start, 7 if i use registerTemplate in every request). 

Both errors, are not noticeable when a single user navigates to this page. (Threading issue maybe?) 

I performed more load tests, having only the data generation code active (without the handlebars rendering part) to see if something on my end causes this behavior but the results were fine. Only when handlebars is used, the memory sky rockets, and many requests start failing. 

I don't know if i can be more specific. Is there anything more i can do for better debugging?
I'll try to reproduce this, in a more simple, demo  environment.

Thanks in advance!

**Comment by nkwinder** [comment]
I've just managed to reproduce this in a minimal demo project.
https://dl.dropboxusercontent.com/u/49017817/handlebars-load-test.zip

p.s all load tests performed using visual studio

**Comment by rexm** [comment]
It seems like two possibly separate problems... the `resolutionCache` errors are simple enough to get around - we can just remove it.  The resource leakage is a bit puzzling. I haven't run into anything like that before with this library. Can you give some details on the load test (what tool, how is it configured) so I can more closely replicate the scenario?

**Comment by rexm** [comment]
I've created [a branch](https://github.com/rexm/Handlebars.Net/tree/Issue-%2312) that has the resolution cache removed from the PathBinder. Can you pull that down and build it locally in release, and run your test again?

**Comment by nkwinder** [comment]
For the tests i use visual studio "Web performance and load test project" project type. I just create a WebTest with a reuest to the url i have locally, and then a load test with the default settings (25 users, 5 min).

I've done the new test as you recomended, and now the failed requests are fewer (38/1846).

This time the errors are the following 2: 

![handlebarserror2](https://cloud.githubusercontent.com/assets/1158542/5597386/2edb8a70-92aa-11e4-9e1f-aaec7660a981.JPG)
![handlebarserror1](https://cloud.githubusercontent.com/assets/1158542/5597385/2edaafa6-92aa-11e4-87bd-88494983a956.JPG)

The cpu and memory situation is the same.

thank you! 

p.s Happy new year! :)

**Comment by rexm** [comment]
Heh, I forgot to actually commit my change to the branch. You should re-run now with zero errors.

Separately, I set up a console app that mimics your demo project by spinning off 100's of threads, executing the template 10000's of times. I cannot see a significant spike in memory consumption... need to keep digging.

**Comment by nkwinder** [comment]
wow. With this fix, not only 0 erros produced (in 5000 total requests), but no memory problem! 
The cpu is increased about 10-15% during the load test (althought compiled view is cached) but maybe this is something that we must live with, in high traffic scenarios.

**Comment by rexm** [comment]
Excellent! To be honest, I didn't fully understand the purpose of the `resolutionCache` when I accepted that PR - on the surface, it appears that it would create a separate instance of the cache for every instance of the template, which would be pointless and definitely cause a memory leak, but I didn't inspect it closely enough to be sure. My mistake!

**Comment by rexm** [comment]
There are always more optimizations to be made... if performance at that volume is unacceptable for you, your high-volume scenarios would be an excellent test bed to instrument with a tool like dotTrace and see where we can make more refinements.

**Comment by nkwinder** [comment]
Thank you for your quick response, and your quick fix! :) I guess this will find its way to the master pretty soon :)
I'll happily give feedback, in case i see anything that can be optimized further!

**Comment by rexm** [comment]
Fix merged to master in 66cd308662fa087340fe85c3d6efceff2d64531a and updated nuget.org version 1.0.4
