### ISSUE TITLE
Access to parent context not working inside custom helper which is inside #each

### ISSUE THREAD

**Issue by jmjv** [rexm/Handlebars.Net#127]
It appears that access to a parent context from within a custom conditional helper doesn't work if that is embedded in an #each block helper or perhaps there is something special that needs to be done that I'm not aware of.

This works: {{#alwaysTrue}}{{parentValue}}{{/alwaysTrue}}
This works: {{#each list}}{{../parentValue}}{{/each}}
This doesn't work: {{#each list}}{{#alwaysTrue}}{{../parentValue}}{{/alwaysTrue}}{{/each}}

Full example code:

```C#
string text = @"{{{HelloWorld}}}
This will work: {{{replaceText HelloWorld ""World"" ""John""}}}.
This will ALSO work: {{#if 1=1}}{{{replaceText HelloWorld ""World"" ""John""}}}{{/if}}.
This will ALSO work: {{#alwaysTrue}}{{{replaceText HelloWorld ""World"" ""John""}}}{{/alwaysTrue}}.
{{#each People}}
{{{this.Name}}} is {{{this.Age}}} years old. 
This will work: {{{replaceText ../HelloWorld ""World"" this.Name}}}.  
This will work: {{#if 1=1}}{{{../HelloWorld}}}{{/if}}.
This will work: {{#if 1=1}}{{{replaceText ../HelloWorld ""World"" this.Name}}}{{/if}}.
This will NOT work: {{#alwaysTrue}}{{{replaceText ../HelloWorld ""World"" this.Name}}}{{else}}never see this{{/alwaysTrue}}.
This will NOT work either: {{#alwaysTrue}}{{{../HelloWorld}}}{{else}}never see this{{/alwaysTrue}}.
{{/each}}
";

dynamic model = new ExpandoObject();
model.HelloWorld = "Hello World";
model.People = new object[] { new { Name = "John", Age = 46 }, new { Name = "Marcia", Age = 43 } };

Handlebars.RegisterHelper("alwaysTrue", (writer, options, context, arguments) =>
{
	if (true)
	{
		options.Template(writer, context);
	}
	else
	{
		options.Inverse(writer, context);
	}
});

Handlebars.RegisterHelper("replaceText", (writer, context, args) =>
{
	if (args.Length < 2)
	{
		return;
	}
	string value = args[0].ToString();
	string search = args[1].ToString();
	string replace = String.Empty;
	if (args.Length >= 2)
	{
		replace = args[2].ToString();
	}
	value = value.Replace(search, replace);
	writer.Write(value.Trim());
});

var template = Handlebars.Compile(text);
string output = template(model);
```

Gives this output:

Hello World
This will work: Hello John.
This will ALSO work: Hello John.
This will ALSO work: Hello John.

John is 46 years old. 
This will work: Hello John.  
This will work: Hello World.
This will work: Hello John.
This will NOT work: .
This will NOT work either: .

Marcia is 43 years old. 
This will work: Hello Marcia.  
This will work: Hello World.
This will work: Hello Marcia.
This will NOT work: .
This will NOT work either: .

**Comment by rexm** [comment]
This is another symptom of the same issue reported in #107. In the "This will NOT work" cases, if you use `../../propertyName` instead of `../propertyName`, it will resolve the value as expected.

Don't have a fix for this yet... it is a symptom of the iterator creating an extra layer of context.

**Comment by jmjv** [comment]
Thanks!
