### ISSUE TITLE
Why does RegisterTemplate and RegisterHelper lock on typeof(Handlebars)?

### ISSUE THREAD

**Issue by pgrm** [rexm/Handlebars.Net#131]
Hi, I wanted to use this library in an ASP.Net application as a way to generate HTML for an HTML-to-PDF processor. Potentially the service would receive multiple requests per second and it seems to me like this library would become the bottleneck.

In [HandlebarsEnvironment.cs line 71-93](https://github.com/rexm/Handlebars.Net/blob/ff6bcacd6041fc07f6fdd85b1ecb57395d3b5417/source/Handlebars/HandlebarsEnvironment.cs#L71) I found locks on the `Handlebars` type such as:

    lock (typeof(Handlebars)) { ... }

I was wondering if this couldn't be replaced by a lock on an instance variable. I found those locks only in that class and instance variables are used within the locks. Obviously, this wouldn't improve the performance of the compilation of one template, but after that change I could compile multiple templates in parallel.

Or are there any issues I've missed? Thanks

**Comment by rexm** [comment]
Probably missed during the refactor to support multiple instances. PR welcome.

**Comment by pgrm** [comment]
@rexm PR is ready :smile:
