### ISSUE TITLE
#each not working for model like IDictionary<int, object>

### ISSUE THREAD

**Issue by michal-ordelt** [rexm/Handlebars.Net#138]
When I change model in Test BasicDictionaryEnumerator to 
```
var data = new
 {
        enumerateMe = new Dictionary<int, object>
        {
                { 42, "hello" },
                { 1000000017, "world" }
        }
};
```
then the test fails.

I guess it is caused by 
`var keys = keysProperty.GetGetMethod().Invoke(target, null) as IEnumerable<object>;`
in `IteratorBinder.Iterate`
when changed to
`var keys = keysProperty.GetGetMethod().Invoke(target, null) as IEnumerable;`
then it works

**Comment by rexm** [comment]
Thanks! Looks like you already did the hard part, PR welcome and you'll get the credit for it too :)
