### ISSUE TITLE
HandlebarsJs.Net linking/rendering CSS styles

### ISSUE THREAD

**Issue by sri7vasu** [rexm/Handlebars.Net#144]
I am trying to render CSS along with my HTML in C#.net class file as follows, but the styles are not rendering. Everything else is working fine. How shall I link the style sheets?

```
string source =
@"<html>
  <head>
  <style type=""text/css"" href="styles.css">
  </head>
  <body>
   <div>
    <h1>{{title}}</h1>
    <div class="myclass">
     {{body}}
    </div>
   </div>
 </body>
 </html>";

var template = Handlebars.Compile(source);

var data = new {
    title = "My new post",
    body = "This is my first post!"
};

var result = template(data);
```

**Comment by rexm** [comment]
Can you elaborate on "the styles are not rendering"? What is the content of `result` in your example above? What is the undesired behavior you are observing?

**Comment by sri7vasu** [comment]
When i link the style sheet as mentioned above, and trying to apply the style to one of the element, for e.g <div class="myclass"> . i could not see the style getting applied in my final output where i am writing this html to a PDF file. Kindly let me know if you need more clarification.

**Comment by rexm** [comment]
That doesn't sound like it has anything to do with Handlebars.Net. What is the content of `result` in your example?

**Comment by sri7vasu** [comment]
This is the content in the result
```
<html>
  <head>
  <style type=""text/css"" href="styles.css">
  </head>
  <body>
   <div>
    <h1>My new post</h1>
    <div class="myclass">
    This is my first post!
    </div>
   </div>
 </body>
 </html>
```

But my Style is not getting applied in the Html as far as i can see.

**Comment by rexm** [comment]
Applying the CSS has nothing to do with Handlebars.Net. Handlebars just takes a template and produces a string as the output. That string is what you just shared above. If that string is HTML, and you pass that HTML into some kind of rendering engine, it's on the engine to correctly "apply" styles.

**Comment by sharadcp** [comment]
It does not support external css file and it is not problem of Handlebar.net. But it works if you declare style in head of your source html like.
<head>
<style>
    .sub-total{
        font-weight:bold;
        color : red;
    }
    .grand-total {
            font-weight: bold;
            color: red;
        }
</style>
</head>

**Comment by sri7vasu** [comment]
I have tried that already and it didn't work as well.The worst part is its displaying whatever is in the <style>  tag on the pdf page instead of applying the style.

Do you have any working example or reference of above mentioned approach? I would like to take a look and see if I am doing anything wrong. Thank you!

**Comment by sri7vasu** [comment]
Never mind, the problem is with the Itextsharp.dll we are using to render the css to the pdf file. Handlebar.net is rendering both the linked style sheets, inline styles and styles defined in the head as well. Thank you every one !
