### ISSUE TITLE
Question: Why handlebars class is static

### ISSUE THREAD

**Issue by matjanos** [rexm/Handlebars.Net#146]
Is there any reason for keeping the main class in the library as static (in fact all members are static). It limits the small scope of use cases.

Is there any reasonable argument for this decision, or it could be changed?

**Comment by rexm** [comment]
Handlebars.Net is intended to provide a very similar experience in .NET to what the original handlebarsjs library provides in JavaScript. In JS, the handlebars library registers a default handlebars object on the root scope for convenience and ease of use for simple cases; static accomplishes the same here.

Also as with the JavaScript library, there is a Create() method on the default instance that returns a new, self-contained handlebars instance if you don't want to use the static one.

**Comment by matjanos** [comment]
Fair enough! I see the concept!
