### ISSUE TITLE
# inside an partial expression resulting error 

### ISSUE THREAD

**Issue by darani73** [rexm/Handlebars.Net#148]
If there is a #(hash) inside an partial expression (e.g {{>#partialName}} the binder crashes ("Reached end of template before block expression was closed").

This is not happening in js library, so templates written for client side binding, might not work in server!

thanks

**Comment by rexm** [comment]
Thanks, can you provide a failing test case?

**Comment by darani73** [comment]
Please find the attached test example, hope it helps you to understand the problem in a better manner :+1: 




![sample result](https://cloud.githubusercontent.com/assets/20199664/18001262/86b212c6-6b9f-11e6-9fda-2e298ae75e40.jpg)

**Comment by huysentruitw** [comment]
Am I correct that this "Partial Block" feature is currently not supported @rexm? See "Partial Blocks" on this page http://handlebarsjs.com/partials.html

**Comment by rexm** [comment]
@huysentruitw I am pretty sure that's correct - the partial block syntax probably wont work right now.

**Comment by rexm** [comment]
Partial block support included in the 1.8.0 release now live on NuGet
