### ISSUE TITLE
missing iOS support

### ISSUE THREAD

**Issue by Ondra09** [rexm/Handlebars.Net#153]
If possible, it would be nice to have iOS support & Xamarin.

iOS limitations:
https://developer.xamarin.com/guides/ios/advanced_topics/limitations/

**Comment by rexm** [comment]
PR always welcome!

**Comment by Ondra09** [comment]
Problem is that, iOS does not supporty dynamic types. I managed to run some example of expression trees on iOS but Handlebars are not working... I don't understand Handlebars.net so deeply that I could say where is problem or how much of the code needs to be changed...

**Comment by rexm** [comment]
As long as iOS doesn't support code generation, it won't be able to support this library.
