### ISSUE TITLE
ArgumentException with Example Code

### ISSUE THREAD

**Issue by shanefulmer** [rexm/Handlebars.Net#154]
Using the latest Nuget package (1.7.1) and the sample code in the Usage block of the Readme, I'm getting the following error on the Compile call:

"Additional information: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type."

**Comment by rexm** [comment]
I can't reproduce this... can you provide more info about your setup?

**Comment by BigLoopy** [comment]
I am also having the same issue with 1.7.1 running Microsoft.NET 4.6 (not mono) and using the example from the front page.

**Comment by rexm** [comment]
When I run the test suite on Windows, it is using framework version 4.6.1586.0 and runtime 4.0.30319.42000 on Windows 10 without issue. Without more information about the specifics of your setup, I don't have enough information to help.

**Comment by chandermani** [comment]
I had a similar issue and it turned out that my Visual Studio settings were the culprit. Make sure you have "Just My Code" setting checked in setting

**Comment by Leftyx** [comment]
I have the same issue.
To recreate you can create a console application and register an helper.
This [line](https://github.com/rexm/Handlebars.Net/blob/master/source/Handlebars/BuiltinHelpers.cs#L55) triggers the exception.

**Comment by jgilbert2017** [comment]
same issue here.
