### ISSUE TITLE
Inline partials are not working

### ISSUE THREAD

**Issue by couellet** [rexm/Handlebars.Net#155]
I am trying to use inline partials:

``` html
{{ #*inline "address" }}
    {{ fullName }}
    {{ #if company }}
        {{ company }}
    {{ /if }}

    {{ address1 }}

    {{ #if address2 }}
        {{ address2 }}
    {{ /if }}

    {{ city }},

    {{ #if province }}
        {{ province }},
    {{ /if }}

    {{ country }}
    {{ postalCode }}
    {{ phone }}
{{ /inline }}
```

Then:

``` html
{{ #with order.billingAddress }}
    {{ #> address }}
{{ /with }}
```

However, I am getting the following error:

```
Template references a helper that is not registered. Could not find helper '#*inline'
```

You can find documentation for inline partials in [Handlebar.js documentation](http://handlebarsjs.com/partials.html#inline-partials).

**Comment by rexm** [comment]
Inline partials are not yet supported... it is on the roadmap though.

**Comment by fabianosuet** [comment]
@rexm - I am already using the lib in production and I am interested in contribute. If you need help to implement the Inline partials stuff, just let me know!

**Comment by rexm** [comment]
PR always welcome! Dive in :)

**Comment by rexm** [comment]
Changes included in the 1.8.0 release now live on NuGet

**Comment by rexm** [comment]
We should implement decorators to support inline partials.

**Comment by cdokolas** [comment]
I consider inline partials very important because of the ability to define everything inside one template (look ma, no code!). Very important when writing (and testing) stand-alone templates.

Please implement them soon!

**Comment by rexm** [comment]
If you don't want to wait, PRs are always welcome @cdokolas!

**Comment by cdokolas** [comment]
@rexm It would be great if I could contribute. I hope to find the time to give it a shot. Wish me luck!

**Comment by jokin** [comment]
#221 adds support to inline partials.

**Comment by huysentruitw** [comment]
Can we close this issue?
