### ISSUE TITLE
Add line number in handlebars exceptions

### ISSUE THREAD

**Issue by couellet** [rexm/Handlebars.Net#156]
It would be awesome to have line numbers in exceptions thrown when compiling templates. 

We are using your library (awesome btw) to add a email template editor in the dashboard of our SAAS directly and it would be nice to display nice errors to the customer when he saves the template ;)

We'll try to contribute on it if we can find some time! Keep up the good work.

**Comment by rexm** [comment]
That's an interesting problem, since after the initial lexer pass, we don't have any context that would tell us what line number traces back to the logical syntax word we're trying to turn into a valid expression!

**Comment by rexm** [comment]
This is being considered in the [2.0 roadmap](https://github.com/rexm/Handlebars.Net/issues/294).
