### ISSUE TITLE
Is support for partial blocks implemented?

### ISSUE THREAD

**Issue by johnfrings** [rexm/Handlebars.Net#157]
[http://handlebarsjs.com/partials.html#partial-block](http://handlebarsjs.com/partials.html#partial-block)

I'm getting an error when trying to use a partial for layout:

`> Could not find helper '#>'`

Is this because '#>' isn't implemented or because I'm doing something fundamentally wrong?

This happens in a template that contains:

```
{{#> default-layout }}
<p>My content</p>
{{/default-layout}}
```

..where default-layout is a registered partial who's template contain something like:
```
<html>
<head></head>
<body>
<div>
{{> @partial-block }}
</div>
</body>
</html>
```

**Comment by rexm** [comment]
Will push an update to NuGet with this fix later this evening.

**Comment by johnfrings** [comment]
I must say that was a rediciously fast reaction, awesome :)

**Comment by rexm** [comment]
That's become a commonly-used feature since I started this project, so it's been bugging me and this issue was the last nudge to go ahead and try to implement it. Ended up being a pretty straightforward addition.

**Comment by rexm** [comment]
Changes included in the 1.8.0 release now live on NuGet

**Comment by fpotter** [comment]
Hey @rexm, does your latest change support referencing the partial block contents via `{{> @partial-block }}`?

**Comment by rexm** [comment]
No, that capability was not included in the initial implementation of partial blocks.
