### ISSUE TITLE
How to use RTM version's Compile function

### ISSUE THREAD

**Issue by joshgarwood** [rexm/Handlebars.Net#159]
Hi there!

I'm probably missing something obvious, but I am not sure how to actually use the RTM version.  When calling `HandleBars.Compile`, it returns `System.Func<object, string>` and I'm not quite sure what to do with that return value.  That function also seems to require an `arg` parameter of type `object`, but I don't know what it should be.  My guess is that the "Compile" function returns a method that can be used to call populate the template with a model.  My code is below; if anythign looks incorrect please let me know.

Thanks!

```
var templateModel = new {
    headerImage = "http://www.mywebsite.com/coolimage.png"
    toUsername = "Josh"
};
var compiledTemplate = Handlebars.Compile(File.ReadAllText("InviteEmail.html"));
var templateString = compiledTemplate(templateModel);
```

**Comment by rexm** [comment]
This looks right, except I am not sure why you called your last variable `templateString`. The string that comes out of the function is *not* a template, it is the result of actually executing the template against the model object you passed in.

**Comment by joshgarwood** [comment]
ahhh gotcha, yea that's just a poor variable name there.  Thanks for the quick response!

**Comment by rexm** [comment]
Are you having some issue using the library or is everything working as expected?

**Comment by joshgarwood** [comment]
It's working well!  I actually realized my mistake after I wrote the question here, but wanted to be sure I hadn't missed something.  Thanks again, and sorry for the trouble!

**Comment by rexm** [comment]
Glad to hear it's working for you
