### ISSUE TITLE
Any kind of state with cached compiled templates

### ISSUE THREAD

**Issue by JvanderStad** [rexm/Handlebars.Net#162]
Hi there,

I know Handlebars doesn't support state, however, 
I would like to keep some form of state in a single _HandlebarsEnvironment_-instance, which I want to use in a (block)helper, but I also want it to be fast (by caching the compiled templates).

When compiling templates, variables used in (block)helpers are captured in a closure; so when trying to store the templates in a static dictionary this will preserve state.

![image](https://cloud.githubusercontent.com/assets/5426370/19749127/cdd37150-9be6-11e6-9753-e25a66ddccfb.png)

Because of the closure, when I try to reuse the compiled templates in a new  _HandlebarsEnvironment_ instance, the original values of the closure are present, so I can't update my state.

As an alternative I tried to extend the delegate signatures of _HandlebarsHelper_ and _HandlebarsBlockHelper_ with an addional HandlebarsConfiguration parameter (I know, breaking change, I'm not submitting this as a pr... I'm exploring my options). 

I thought, maybe I could preserve state in the Configuration instance, but this also seems to be captured somehow.

``` c#
public delegate void HandlebarsHelper(TextWriter output, dynamic context, *HandlebarsConfiguration configuration*, params object[] arguments);
public delegate void HandlebarsBlockHelper(TextWriter output, HelperOptions options, dynamic context, *HandlebarsConfiguration configuration*, params object[] arguments);
```

See my experimental commit https://github.com/Hybrid-SaaS/Handlebars.Net/commit/81eb8a6ced13392966cf391907f8460d00cd117f

I'm building a project where I'm heavily relying on Handlebars.net. But I'm kind of stuck right now. 
Can you assist me with my attempt to maintain some form of state? I would be very appreciated.

Kind regards

Jeffrey

**Comment by rexm** [comment]
What problem are you trying to solve by attaching state to the environment?

**Comment by JvanderStad** [comment]
# What do I want?#
I want to keep track of data in cached (block)helpers.

Because compilation is a heavy operation, I want to compile and store partials in some caching mechanism. However, when doing so, the active state is captured.

# Example #
I created a sample WinForm application in https://github.com/Hybrid-SaaS/Handlebars.Net/commit/10dca9f0e28313a91be33bc785163d905c8bc958 to showcase my problem. 

![image](https://cloud.githubusercontent.com/assets/5426370/19763348/ea4b3f46-9c3d-11e6-9e1d-721202f28d47.png)

# How to .. #
In the example application I want to keep track of the current language, but when I cache the partials in a static Dictionary, the first selected language is captured and reused.

To simulate what I mean:

- **Checkout** this commit: https://github.com/Hybrid-SaaS/Handlebars.Net/commit/10dca9f0e28313a91be33bc785163d905c8bc958
- **Debug** application from Visual Studio
- Set language to **English**
- Push **Run** button
- Set a **breakpoint** here https://github.com/Hybrid-SaaS/Handlebars.Net/blob/feature/state-example/source/Handlebars/Compiler/Translation/Expression/PartialBinder.cs#L86
- Set a **breakpoint** here https://github.com/Hybrid-SaaS/Handlebars.Net/blob/feature/state-example/source/Example/TemplateCache.cs#L63
- Set language to **Nederlands**
- Push **Run** button again

At line 86:
```c#
configuration.RegisteredTemplates[partialName](context.TextWriter, context);
```

When I quickwatch 
```c#
configuration
````
the value is (as expected) _Nederlands_

![image](https://cloud.githubusercontent.com/assets/5426370/19763944/c2080480-9c40-11e6-8239-5035c2c2925d.png)

When I quickwatch 
```c#
configuration.RegisteredTemplates[partialName]
```
the closure contains a reference to the original config object (value _English_)

![image](https://cloud.githubusercontent.com/assets/5426370/19764013/19c3cda8-9c41-11e6-8a21-2aba7aadeede.png)

Continue execution to break at TemplateCache.cs#L63

```c#
var customConfig = configuration as CustomConfig;
```

When I quickwatch the configuration argument the original state is present (_English_)

![image](https://cloud.githubusercontent.com/assets/5426370/19764176/f5328992-9c41-11e6-9c0a-95d755f1cfa3.png)

# What did I expect? # 
When I changed the code to include the configuration in the delegate, I thought the active instance would be passed to the delegate, however, the original value is stored and passed.

I'm looking for a way to pass some variable(s) to the delegate. 

I hope this explains my problem.

Thanks again 👍

**Comment by rexm** [comment]
This seems like global/application state that cuts across all currently executing instances, is that an accurate characterization?

**Comment by JvanderStad** [comment]
This is true for the delegates, if an single Hangfire instance has its own compiled helpers, the state is different for an other Hangfire instance.

**Comment by JvanderStad** [comment]
Also the state is captured (like a snapshot)

**Comment by rexm** [comment]
I am going to give this some thought over the weekend.

**Comment by JvanderStad** [comment]
Happy days, I just created a workaround. 

I'm using HttpContext.Current.Items to store my state data, in the first tests this seems to work. Maybe because HttpContext.Current is a [ThreadStatic] property?

:thinking: I can imagine the capture of global context with cached (helper) delegates may prevent garbage collection (memory leaks). Not sure though.
