### ISSUE TITLE
Running Handlebars with different configurations

### ISSUE THREAD

**Issue by GennadyPonomarev** [rexm/Handlebars.Net#163]
I'd like to write a webservice which takes template and parameters in and returns rendered text.

It looks like to achieve thatI need to run two handlebars instances in parallel, with different configurations. One will be used for html templates and the other for plain text templates (sms). In the latter case I'll provide custom ITextEncoder. I'm afraid that using static HandlebarsConfiguration from Handlebars class will lead to race conditions (constantly changing ITextEncoder in configuration, running Handlebars.Compile with wrong ITextEncoder will lead to errors in the resulting text).

Is this use case currently supported? I saw a pull request from mikeofireland. He exposed HandlebarsEnvironment, so it can be instancinated with independent configurations. Are there any drawbacks of such approach?

**Comment by JvanderStad** [comment]
This is possible, 

see this unit test

https://github.com/rexm/Handlebars.Net/blob/ed2c609fd30bdefb2ebbd17e25749df0b8afad26/source/Handlebars.Test/CustomConfigurationTests.cs

**Comment by rexm** [comment]
This is already supported by calling Handlebars.Create and passing in a configuration object.

**Comment by GennadyPonomarev** [comment]
Thanks!
