### ISSUE TITLE
Async Helper Method

### ISSUE THREAD

**Issue by starmandeluxe** [rexm/Handlebars.Net#166]
Currently it seems impossible to make a registered helper method have asynchronous calls inside it. I want to do something like this:

Handlebars.RegisterHelper("my_method", async (writer, context, parameters) =>
            {
                var blah  = await _myService.GetBlahAsync(parameters[0]);
                writer.WriteSafeString(blah);
            });

But it ends up closing the writer even before the writesafestring is called.

Can support for this functionality be added?

**Comment by rexm** [comment]
Any I/O bound work you need to do should be done as part of creating the model.

**Comment by starmandeluxe** [comment]
Ah, I see what you mean. Normally I'd agree, but our requirement is to allow parameter passing via the template and I/O is totally based on this parameter. For example, the template will specify an ID, and the corresponding entity is then looked up via this ID during template rendering in the Helper method. Perhaps this is not using Handlebars as intended?

**Comment by rexm** [comment]
The template specifies the lookup ID? That seems odd. A template is a static asset - if you know the ID at authoring time, you can go fetch that data at initialization time and cache it for the lifetime of the template, not re-fetch each time during execution.

**Comment by rexm** [comment]
Or if the object could change, it should be part of a record that is tied to your template so you can look it up as part of constructing the model.

**Comment by sebastienros** [comment]
I have the same requirement actually.

**Comment by priedthirdeye** [comment]
The NodeJs hbs implementation for Express has a registerHelperAsync method. I've used it for several of my use cases.

The following post describes how it works under the hood. 

https://github.com/wycats/handlebars.js/issues/141#issuecomment-44947766

If I had more experience with c# I'd try to port it over.

**Comment by rexm** [comment]
If this notion is incorporated into the core handlebarsjs, we'll add it as well.

**Comment by Lukiya** [comment]
Any update on this, I need the RegisterHelperAsync too.
We'll let user edit the template, so they can call {{GetProductList 43}} to get a furniture(category id:43) picture list.

**Comment by rexm** [comment]
There are no plans currently to support this. The recommended architectural approach is to do all I/O bound work during the construction of your model object, not during template binding.

**Comment by sebastienros** [comment]
Sometimes the logic has no idea what the template might need and there is no way around it. Happens a lot in CMSs where everything is dynamic, and template can't be specialized. 

As much as I understand the restriction as it's out of scope, I had to implement my own library also to overcome this limitation.

**Comment by knightmeister** [comment]
+1 I need this as well.
Are you open to a PR to add it?

#369 in some ways could obviate this to pull out IDs you need and populate the model ahead of time but given there is no ability to parse a document (as far as I can see) I think this is a pretty crucial feature to be able to resolve dependant external inputs to generation. My specific use case is to pull information from a database and interpolate it into the output, which I would think is quite a common requirement.

**Comment by rexm** [comment]
Intermingling fetching and i/o with template rendering doesn’t align with the architecture of Handlebars. Candidly I think if you are headed down the road where you are using Handlebars for rendering and think you need this, you are already confused about the responsibility boundaries in your system.

**Comment by HuwLittle** [comment]
+1 for this - would suit my use case perfectly - is the issue closed as you're not going to make this change?

**Comment by udnes99** [comment]
Another +1 for this! Our use case is also for fetching CMS data that we cannot know ahead of time, but which would be baked into the template. For example, for some entities we both store a long title and a shortened title. In some templates it makes sense to use the former, whereas in others, it would make sense to use the latter. By having the ability to define async helpers, we could let the template decide, and simply inject the id of the entity, and define two different async helpers, one for each title type.

**Comment by alexandreakdeniz-soc** [comment]
+1. Without that the whole strength of handlebar is minimize.

**Comment by rexm** [comment]
We are not going support async helpers, unless the Handlebars JS library adds async helpers (which as far as I know, also does not plan to do).

**Comment by ak293700** [comment]
Thank you for your answer, how much works do you think it represents to fork this repo and add that feature ? What are the things you would warn me about ?

**Comment by rexm** [comment]
"If you have to ask, you can't afford it"

It would be straightforward to get a working prototype in a fork. However, my own experience starting this library over a weekend 10 years ago and it turning into thousands of hours of engineering spread across dozens of contributors, I can say that getting such features to work reliably, predictably, performantly, at scale is a heavy lift.

**Comment by rhegner** [comment]
I read this thread with great interest. Initially I also thought I need async helper methods.

Here is my use-case: I want my user to be able to send templated e-mails. So the template comes from user input. The template can contain all kinds of data, which might be expensive to fetch. Now of course I don't want to fetch all possible data for every e-mail, just because the template _might_ need it. That's why I thought I need async helper methods, so I can go fetch data _as needed_ during rendering. However, on second thought I don't think async helpers is the right solution, at least not for my use case. Much more helpful would be a way to determine what data is actually needed after compiling.

So the pseudo code would look something like this:

```
var template = Handlebars.Compile(userProvidedTemplate);
var requiredObjects = DetermineRequiredObjects(template); // does something like this exist in this library???
foreach (recipient of mailRecipients)
{
    var data = new {
        title = "some data that's not expensive to obtain"
    }
    if (requiredObjects.Contains("orders"))
    {
         // fetch orders for current mail recipient and add to data
    }

    var result = template(data);
}
```

@rexm Is such an approach possible with this library? Is there a way to figure out from a compiled template what objects/keywords are used in the template?

**Comment by rhegner** [comment]
I found a solution that should work for me. So I will try your library in my application :)

```
using HandlebarsDotNet;
using System.Dynamic;

var userProvidedTemplate = """
<p>{{title}}</p>
<p>{{recipient.firstName}}</p>
<p>{{recipient.lastName}}</p>
<ul class="order_list">
  {{#each orders}}
    <li>{{this}}</li>
  {{/each}}
</ul>
""";

// Compile
var template = Handlebars.Compile(userProvidedTemplate);

// Analyze
var templateAnalyzer = new TemplateAnalyzer();
var _ = template(templateAnalyzer);

// Render (this would be done in a loop for a large number of recipients)
{
    var data = new Dictionary<string, object>
    {
        { "title", "Order confirmation" },
        { "recipient", new { firstName = "John", lastName = "Doe" } }
    };

    if (templateAnalyzer.TemplateRequiresOrders)
    {
        // In real life this would be an expensive (asynchronous) fetch we only want to do
        // if the user-provided template requires it
        var orders = new List<string> { "Order 1", "Order 2", "Order 3" };
        data.Add("orders", orders);
    }

    var result = template(data);
    Console.WriteLine(result);
}




class TemplateAnalyzer : DynamicObject
{
    public override bool TryGetMember(GetMemberBinder binder, out object? result)
    {
        if (binder.Name == "orders")
            TemplateRequiresOrders = true;

        return base.TryGetMember(binder, out result);
    }

    public bool TemplateRequiresOrders { get; private set; } = false;
}
```
