### ISSUE TITLE
False If resulting in next handlebars block not being evaluated correctly

### ISSUE THREAD

**Issue by codeplay87** [rexm/Handlebars.Net#17]
First of all great work on the c# handlebars engine. We have come across a bug where by when an if block results to false the preceding handlebars pure html block is not evaluated correctly. 

Here is a failing test we have written to simulate the issue described.

```C#
[Test]
public void FailingBasicTripleStash()
{
string source = "{{#if a_bool}}{{{dangerous_value}}}{{/if}}Hello, {{{dangerous_value}}}!";

var template = Handlebars.Compile(source);

var data = new
{
a_bool = false,
dangerous_value = "<div>There's HTML here</div>"
};

var result = template(data);
Assert.AreEqual("Hello, <div>There's HTML here</div>!", result);
}
```

Thanks,
We Are Colony Dev Team.

**Comment by rexm** [comment]
When I run the test, I get an encoded output instead of the expected un-encoded output. Is that also what you see?

**Comment by codeplay87** [comment]
Yes so here it the result of the test when I am running it.

  Expected string length 36 but was 52. Strings differ at index 7.
  Expected: "Hello, <div>There's HTML here</div>!"
  But was:  "Hello, &lt;div&gt;There&#39;s HTML here&lt;/div&gt;!"

**Comment by rexm** [comment]
Updated NuGet 1.1.3
