### ISSUE TITLE
.NET version compatibility?

### ISSUE THREAD

**Issue by sp00x** [rexm/Handlebars.Net#175]
Based on the readme.md here I am not quite sure what the minimum .NET version is, but it seems to be 4.0 based on what I managed to pull from NuGet, and the fact that I couldn't compile using VS2012 (yes, sorry)?

(I have a large 3.5 project I haven't been able to upgrade yet..)

Would be good to at least clarify on the page what the version requirement is. Sorry if it says but I'm blind :)

**Comment by rexm** [comment]
The library supports .NET 4.5+ and dotnet core 1.

**Comment by StefH** [comment]
It actually only supports **NetStandard 1.5** and up. I'll take a look if I can change that.

**Comment by rexm** [comment]
It definitely supports .NET 4.5... the core/standard naming I've lost patience with. So let's just say ".NET 4.5 and also the new stuff whatever that's called"

**Comment by StefH** [comment]
What I mean to say is that I want to check if it;s possible to support **NetStandard 1.3** and up.

**Comment by StefH** [comment]
See PR : https://github.com/rexm/Handlebars.Net/pull/182

**Comment by sandorfr** [comment]
Really nice @StefH that you have improved it to support `NetStandard 1.3` ! That goog they brought back reflection without GetTypeInfo() in 4.3.0... so much cleaner !

**Comment by asiffermann** [comment]
At the moment with the version 1.8.0, I cannot get it work with a .NET Core web application targeting net462:
- It is working with net45, net451, net452, net46 and net461: it takes the portable library
- It is working with netcoreapp: it takes the netstandard1.5 version
- With net462 it is trying to take the netstandard1.5, but I have an exception at runtime "FileLoadException: Could not load file or assembly 'Handlebars, Version=1.0.0.0..."

I just pulled the project, build it, pack it using the `_build nuget.cmd` file that @StefH included in his PR, and uploaded the NuGet package to a MyGet feed (https://www.myget.org/feed/gl-unstable/package/nuget/Handlebars.NetStandard), and it solved my issue!

The generated nuspec file is slightly different from the one you use to package your library, so maybe you should publish the new package with it:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Handlebars.NetStandard</id>
    <version>1.8.1</version>
    <title>Handlebars</title>
    <authors>Rex Morgan,Stef Heyenrath</authors>
    <owners>Rex Morgan</owners>
    <projectUrl>https://github.com/rexm/Handlebars.Net</projectUrl>
    <iconUrl>https://raw.githubusercontent.com/rexm/Handlebars.Net/master/hbnet-icon.png</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Blistering-fast Handlebars.js templates in your .NET application.</description>
    <summary>Blistering-fast Handlebars.js templates in your .NET application.</summary>
    <releaseNotes>Now supports net standard 1.3</releaseNotes>
    <tags>handlebars,mustache,templating,engine,compiler</tags>
    <dependencies>
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETPortable4.0-Profile24" />
      <group targetFramework=".NETStandard1.3">
        <dependency id="Microsoft.CSharp" version="[4.3.0, )" />
        <dependency id="System.Collections" version="[4.3.0, )" />
        <dependency id="System.Diagnostics.Debug" version="[4.3.0, )" />
        <dependency id="System.Dynamic.Runtime" version="[4.3.0, )" />
        <dependency id="System.Globalization" version="[4.3.0, )" />
        <dependency id="System.Linq" version="[4.3.0, )" />
        <dependency id="System.Reflection" version="[4.3.0, )" />
        <dependency id="System.Reflection.Extensions" version="[4.3.0, )" />
        <dependency id="System.Reflection.TypeExtensions" version="[4.3.0, )" />
        <dependency id="System.Runtime.Extensions" version="[4.3.0, )" />
        <dependency id="System.Text.RegularExpressions" version="[4.3.0, )" />
        <dependency id="System.Threading" version="[4.3.0, )" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETPortable4.0-Profile24" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETPortable4.0-Profile24" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETPortable4.0-Profile24" />
      <frameworkAssembly assemblyName="System.Net" targetFramework=".NETPortable4.0-Profile24" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETPortable4.0-Profile24" />
    </frameworkAssemblies>
  </metadata>
</package>
```

Do you have any insight when you are going to publish the 1.8.1 version that solve the compatibility issue with net462?

Thank you!

**Comment by rexm** [comment]
Make a PR with the corrections/improvements

**Comment by StefH** [comment]
Do you mean you need to manually update the nuget file?

Note that this file is not used with the nugetbuild.cmd file.

**Comment by asiffermann** [comment]
See PR #186

**Comment by sandorfr** [comment]
@rexm now the PR is merged, is there a chance you will push an updated 1.8.1 to nuget anytime soon?

**Comment by rexm** [comment]
Now that dotnet core/standard seems to be better-understood by the community, I'm going to close this issue. Handlebars.Net currently supports `net452`, `netstandard1.3`, and `netstandard2.0`
