### ISSUE TITLE
How can I achieve a raw block helper?

### ISSUE THREAD

**Issue by dancvogel** [rexm/Handlebars.Net#179]
I'm trying to compile a handlebars template server side that has a handlebars template in it that I want to compile clients side. The Handlebars documentation has this:

[http://handlebarsjs.com/block_helpers.html](http://handlebarsjs.com/block_helpers.html)
Raw Blocks

Raw blocks are available for templates needing to handle unprocessed mustache blocks.
```
{{{{raw-helper}}}}
  {{bar}}
{{{{/raw-helper}}}}
```
will execute the helper raw-helper without interpreting the content.
```
Handlebars.registerHelper('raw-helper', function(options) {
  return options.fn();
});
```
will render

```
{{bar}}
```

However, my attempt using Handlebars.Net still seems to be compiling the inner block. 
```
{{{#raw-helper}}}
      {{myhelper key}}
{{{/raw-helper}}}
```
```
Handlebars.RegisterHelper("raw-helper", (writer, options, context, parameters) =>{
                options.Template(writer, null);
            });
```
And so I'm getting an error that the helper myhelper is undefined, which is true for this pass since myhelper is defined client side.

If I use {{{{raw-helper}}}} I get the error: "Reached unparseable token in expression: {raw-helper}}}}"

Note: I'm using Handlebars.Net version 1.7.1, I'd prefer not to update yet, but will if it will help get me to where I want to be.

**Comment by rexm** [comment]
We don't yet support the quadrouple-stash syntax for raw block helpers.

**Comment by DanielAlonsoPardo** [comment]
Hello, concerned citizen here. Any idea of when this change might be implemented? Also, why is the quad-mustache syntax even mentioned in https://handlebarsjs.com/expressions.html and https://handlebarsjs.com/block_helpers.html ??? It's been that way for years and it is really misleading when your code doesn't work.

-concerned citizen

**Comment by rexm** [comment]
This project is an ongoing effort to build a .NET implementation that has parity with the JS implementation. So there are features like the quad stache that we haven’t gotten to yet.

**Comment by rexm** [comment]
If it is causing you trouble and you can’t wait, you’re welcome to submit a PR that adds support for it.
