### ISSUE TITLE
implement @root (access root context)

### ISSUE THREAD

**Issue by nkwinder** [rexm/Handlebars.Net#18]
It would be nice to support this

https://github.com/wycats/handlebars.js/blob/271106d43fae96fc1287898568d000b871f19084/spec/data.js#L223

http://stackoverflow.com/questions/17364897/access-to-root-context-in-handlebar-js-template

**Comment by rexm** [comment]
Go for it :)

**Comment by rexm** [comment]
NuGet 1.1.7

**Comment by amellini** [comment]
How can i add or edit root variable in an helper?
