### ISSUE TITLE
Custom Partial Resolution

### ISSUE THREAD

**Issue by tomtrias** [rexm/Handlebars.Net#180]
We have a lot of templates organized in a folder hierarchy that we load on demand.  We would like to be able to use _"path relative"_ partials, which can still be resolved at template compilation time, so we would accept the requirement that the resolution be idempotent.

In order to achieve this without having to hard-code the new resolution logic into `Handlebars.Net`, it would be ideal if the `HandlebarsConfiguration` could contain a new property `PartialPathResolver`, presumably of the new `IPartialPathResolver` type.

**Comment by rexm** [comment]
PR always welcome

**Comment by tomtrias** [comment]
Hopefully I can find some time next week.  :-)
