### ISSUE TITLE
Can't get #if to work

### ISSUE THREAD

**Issue by nickhow83** [rexm/Handlebars.Net#181]
Hello, I'm struggling to get #if to work with compiled templates.  Everything else seems to work OK and the template works on a JSFiddle I have with the same data.

http://jsfiddle.net/nickhow83/xsry8msk/

My problem is that I use a truthy value for the `server` property but the #if block isn't evaluating it and rendering the content.

**Comment by rexm** [comment]
Given the following code (converted exactly from your JS example):
```
string source = 
@" <FONT SIZE=11pt COLOR='black' FACE='Calibri'>
      	<p><B>Task Alert</B></p>
        <p>{{description}}</p>
        {{#if server}}
        <p>Please click <a href=""http://{{server}}/cases/{{caseRef}}/tasks/{{taskId}}"">here</a> to view more details</p>
        {{/if}}
        <p>Client Number: {{clientRef}}</p>
        <p>Case Number: {{caseRef}}</p>
        <p>Case Description: {{caseDescription}}</p>
        {{#if comment}}
        <p>Comments:<br>{{comment}}</p>
        {{/if}}
        <p>THIS IS SYSTEM GENERATED, PLEASE DO NOT REPLY.</p>
  </FONT>";

var template = Handlebars.Compile(source);

var data = new {
    server = "test-server",
    taskId = 12345,
    description = "A new task",
    caseRef = "1254",
    clientRef = "999",
    caseDescription = "Case description"
};

var result = template (data);
```

The output is:
```
 <FONT SIZE=11pt COLOR='black' FACE='Calibri'>
      	<p><B>Task Alert</B></p>
        <p>A new task</p>
        <p>Please click <a href="http://test-server/cases/1254/tasks/12345">here</a> to view more details</p>
        <p>Client Number: 999</p>
        <p>Case Number: 1254</p>
        <p>Case Description: Case description</p>
        <p>THIS IS SYSTEM GENERATED, PLEASE DO NOT REPLY.</p>
  </FONT>
```

This appears to be working correctly. Can you please share the c# code that _isn't_ working, instead of sharing some Javascript that is working? As well, please include the data for your test case.

**Comment by nickhow83** [comment]
here is the snippet of code from my application
```CS
var templatePath = Path.Combine(HostingEnvironment.MapPath("~/Templates/Handlebars/"), "TaskEmail.html");
template = Handlebars.Compile(File.ReadAllText(templatePath));
body = template(request.Data);
message = request.ToNetMailMessage(body);
```

**Comment by nickhow83** [comment]
It's ok, I've figured it out.  It's because the data was a dynamic object that was being passed across a service boundary.  The content was there but it looks as though #if doesn't play nicely with a dynamic object

**Comment by randylsu** [comment]
Just ran into this as well with string properties on a dynamic object.  The .Value work-around may get me by, but would be great if it worked as expected. I'll do some digging into the unit tests & see if I can figure something out.

**Comment by leosdad** [comment]
Unfortunately Handlebars.Net doesn't seem to work correctly inside `@each` when reatrieving values from an array. Consider the template below:
```handlebars
{{#each items}}
	<b>{{item.name}}:</b>
	{{#if item.description}}
		<p>Description: {{item.description}}</p>
	{{/if}}
	<br />
{{/each}}
```
With the data:
```javascript
var data = { 
    items: [
    	{
        item: {
          name: 'First item',
          description: 'This one has a description'
        }
      },
    	{
        item: {
          name: 'Second item'
          // This one has no description
        }
      }
    ]
};
```
In handlebars.js it works as expected (see http://jsfiddle.net/bkn4yLg7/3/):
```html
<b>First item:</b>
Description: This one has a description
<br />
<b>Second item:</b>
<br />
```
For Handlebars.Net I've used the following JSON and `NewtonSoft.Json.JsonConvert.DeserializeObject()`:
```json
"items": [
  {
    "item": {
        "name": "First item",
        "description": "This one has a description"
    }
  },
  {
      "item": {
        "name": "Second item"
  }
}
]
```
...but in the output is:
```html
<b>First item:</b>
<br />
<b>Second item:</b>
<br />
```
If anyone knows a solution, please help. Thanks.

**Comment by rexm** [comment]
@randylsu's comment directly above yours notes the solution:
>Deserializing explicitly to ExpandoObject rather than dynamic resulted in the expected behavior.

Implicit deserialization in Newtonsoft produces a JObject, which is a specialized kind of object specific to Newtonsoft that Handlebars.Net doesn't understand. If you explicitly deserialize your JSON to a BCL type like Expando or a POCO, you'll find it behaves as expected (and also performs about 10x faster).

**Comment by edwardaskew** [comment]
Any idea on why this happens for JObjects though? As far as I can see everything else works with them and Handlebars.Net does claim to work for dynamic objects, not just certain types of dynamic objects.
