### ISSUE TITLE
Add an extra test with shows that you can do some nice tricks with a List

### ISSUE THREAD

**Issue by StefH** [rexm/Handlebars.Net#183]
Actually this test is inspired on the documentation from WireMock.org:

- request.query.<key>- First value of a query parameter e.g. request.query.search
- request.query.<key>.[<n>]- nth value of a query parameter (zero indexed) e.g. request.query.search.[5])

This can be shown by this unit-test:
```c#
/// <summary>
/// A special HandlebarsList which overrides the ToString() to return first value.
/// </summary>
private class HandlebarsList<T> : List<T>
{
	public HandlebarsList(IEnumerable<T> collection) : base(collection)
	{
	}

	public override string ToString()
	{
		if (this.Any())
			return this.First().ToString();

		return base.ToString();
	}
}

[Test]
public void BasicPathSpecialList()
{
	var source = "Hello {{ list }} {{ list.[0] }} {{ list.[1] }}";
	var template = Handlebars.Compile(source);
	var data = new
	{
		list = new HandlebarsList<string>(new [] { "x", "y" })
	};
	var result = template(data);
	Assert.AreEqual("Hello x x y", result);
}
```

Maybe a good idea to add this to the unit-tests?

**Comment by rexm** [comment]
This test would be redundant, since we already have tests that ensure indexers (`x.[n]`) work and that we call `ToString()` on objects that don't have a separate native string representation.

**Comment by StefH** [comment]
Ok. Perfect.
