### ISSUE TITLE
Handlebars.Net not handling expressions correctly

### ISSUE THREAD

**Issue by thehappybug** [rexm/Handlebars.Net#188]
Handlerbars fails to handle expressions like:

* `this.[somename]`
* `this.[some name]`

Here is my sample code:

```csharp
string source =
@"<div class=""entry"">
<h1>{{ this.[post title] }}</h1>
<div class=""body"">
{{ this.'body' }}
</div>
</div>";

var template = Handlebars.Compile(source);

var json = @"{""post title"" : ""Mynew post"", ""body"" : ""some body we have here""}";

var data = JsonConvert.DeserializeObject<dynamic>(json);

var result = template(data);
```

The result is

```html
<div class="entry">
<h1></h1>
<div class="body">

</div>
</div>
```

This makes it difficult to link to properties that are not valid identifier names.

Is there a workaround for this issue? I need to use the same templates on my client side (JS) where my example template works fine.

**Comment by rexm** [comment]
The `[name]` syntax is supported for dictionaries, but not JObjects yet. You can use a [custom JsonConverter](http://stackoverflow.com/a/31250524/67) to deserialize to a nested `Dictionary<string, object>` instead of a `dynamic` and that should work as expected.
