### ISSUE TITLE
Need Nuget package for new 1.2 release

### ISSUE THREAD

**Issue by EBMike** [rexm/Handlebars.Net#190]
The last published package is from Sunday, October 9, 2016 (v1.8.0)

**Comment by StefH** [comment]
@EBMike What do you mean with `new 1.2 release` ? I think you mean to say `NETStandard 1.3` ? --> See also https://github.com/rexm/Handlebars.Net/issues/175

**Comment by EBMike** [comment]
@StefH I'm not sure what exactly you mean by Net Standard 1.3 ... all I know is the nuget package published (1.8.0) seems to be seriously out of date. Now, if what your saying is I need to use another nuget package than I would be happy to use that.

**Comment by rexm** [comment]
We are not using Github release tags. The latest version 1.8.0 published to NuGet in October is lacking a couple of minor bug fixes/enhancements and better compatibility with the current state of Net Standard / Net Core which will come when I have some time to fix the build.

**Comment by Meddington** [comment]
I'd be happy to lend a hand re-build issues.  Which build is having issues?

**Comment by StefH** [comment]
Building a nuget package is easy : https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/_build%20nuget.cmd

**Comment by axelheer** [comment]
Hasn't the build already been fixed? (#182)

**Comment by axelheer** [comment]
Maybe moving to the new "Microsoft.NET.Sdk" cleans up the build (#196)

**Comment by niemyjski** [comment]
Can we get the releases section updated, I was looking at the repo and it looked kinda dead, but then I looked at nuget and saw it pretty active.

**Comment by rexm** [comment]
Frankly I just don't always put a lot of effort into the releases section of this repo. The commit activity and the Nuget feed are the best representations of the state of the project.

**Comment by StefH** [comment]
Generating a new NuGet is automatically done in the new vs2017 csproj format. So can you please release a new package on nuget.org ?

**Comment by jchannon** [comment]
Hi, can we get a new release onto nuget please, do you need some help to get this done?

**Comment by jchannon** [comment]
I've had to fork and publish to a private feed but would like to get this repo out onto nuget if you need help

**Comment by jchannon** [comment]
1.9.0 is now out, this can be closed

**Comment by axelheer** [comment]
@rexm how did you make the package? The version (prefix) is 1.8.1 as is the file version of the released package; which doesn't hurt, but doesn't make much sense?

**Comment by rexm** [comment]
@axelheer can you clarify what you mean "the version (prefix) is 1.8.1"?

**Comment by StefH** [comment]
In the file `Handlebars.csproj` you define a versionprefix element.

**Comment by rexm** [comment]
Are you simply saying the master branch doesn't reflect what is in NuGet?

**Comment by jchannon** [comment]
I just looked and the 1.9.0 dll has a version of 1.8.1 :)

**Comment by StefH** [comment]
Best is just delete this line:

https://github.com/rexm/Handlebars.Net/blob/master/source/Handlebars/Handlebars.csproj#L7

**Comment by rexm** [comment]
I am not sure how this happened... my local version is `1.9.0` which is what created the build & pack. Need to figure out where the 1.8.1 came from before trying to update.
