### ISSUE TITLE
Arguments containing closing curly braces are not parsed correctly

### ISSUE THREAD

**Issue by vzwick** [rexm/Handlebars.Net#191]
I have created a very simple helper:

            Handlebars.RegisterHelper("verbatimInline", (output, context, arguments) =>
            {
                output.WriteSafeString(arguments.FirstOrDefault());
            });

When using it inside my template like `Handlebars.Compile(@"{{verbatimInline '{{foo}}'}}");`, the passed argument is `{{foo` as opposed to the expected `{{foo}}`.

Also, when using it like `Handlebars.Compile(@"{{verbatimInline '{{foo}}'}}SOMETHING{{verbatimInline '{{bar}}'}}")` the resulting output is `{{foo'}}SOMETHING{{bar'}}` which leads me to believe that the parser interprets the closing curly braces inside `'` as closing braces rather than as literal.

The same behavior occurs when using double quotes for the arguments.

**Comment by rexm** [comment]
How does the javascript library handle this case?

**Comment by vzwick** [comment]
@rexm it behaves as per spec - arguments enclosed in single quotes are treated as literals. Here's a quick demo: http://jsfiddle.net/vng4ddn4/2/
