### ISSUE TITLE
Signed Packages for the latest versions

### ISSUE THREAD

**Issue by tico321** [rexm/Handlebars.Net#193]
The latest package with a strong name is the release 1.2. It would be good to have a signed package for 1.8

**Comment by tico321** [comment]
Additionally I would like to say that I was using the version 1.8 and everything was going great, but the problem is that I'm integrating my code with other project that has a strong name, in order to do this I downgraded the version to 1.2 as is the last package you provided with a strong name, but now some scenarios that used to work are failing, so I would really appreciate if you sign the 1.8 version.

**Comment by wayrex** [comment]
++

**Comment by ronaldbriguer** [comment]
1+

**Comment by gabitosoft** [comment]
+1

**Comment by niemyjski** [comment]
the .net team recommends just signing all your packages and not creating a specific signed package. It's what we are doing for ours going forward (and less work).

**Comment by ErikEJ** [comment]
Me too! https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/issues/9

**Comment by tonysneed** [comment]
@rexm Are you planning to signing your assembly?  A strongly named assembly need to reference mine, which references yours. :)

**Comment by tonysneed** [comment]
As of [v1.9.4](https://www.nuget.org/packages/Handlebars.Net/1.9.4), the NuGet package is signed.
