### ISSUE TITLE
1.80 Nuget - missing RegisterTemplate(string, string) 

### ISSUE THREAD

**Issue by PartyArk** [rexm/Handlebars.Net#200]
- VS2017, Create new Project > Class LIbrary (.NET Core)
- Install Handlebars.Net 1.80 via NuGet
- Missing Handlebars.RegisterTemplate(string, string) - although RegisterTemplate(string, Action) is present

I've had a look at the disassembled contents of Handlebars.dll, and the method is not present. So I guess the Jan 31 commit is not yet published to NuGet?

I have simply used the github source for now, and it's working fine.

**Comment by rexm** [comment]
The date on Nuget shows it was published October 9, 2016.

**Comment by PartyArk** [comment]
Yes, saw that. But it's confusing because the _readme_ instructions say install from nuget; then, under how to Registering Partials, the `RegisterTemplate(string, string)` method is used. 

So perhaps drop that section until you're ready to publish the updated version?
