### ISSUE TITLE
Loading a partial template from a file

### ISSUE THREAD

**Issue by paulashton** [rexm/Handlebars.Net#201]
I want to be able to define partial templates in .hbs files in a partials sub-directory of the directory that holds the templates. I couldn't see how to do it in either the current release or the current code in this repository. Looking at the code, it appeared that if I was able to compile the main template using CompileView then the compilation should be able to get partials from the the partials sub-directory (without the need for registering the partials using RegisterTemplate). Trouble is the CompileView method in IHandleBars is not exposed by the Handlerbars class. I added the following to Handlebars.cs:

        public static Func<object, string> CompileView(string templatePath)
        {
            return Instance.CompileView(templatePath);
        }

and everything worked fine. The partials were loaded from the partials sub-directory without having to register them (I did have to create a class that extends ViewEngineFileSystem). 

Should I be doing this some other way? Or would it makes sense to add the code above to Handlebars.cs?

**Comment by rexm** [comment]
That looks like an oversight on our part. The static methods on `Handlebars` are intended to give you convenience access to the default instance, so if `IHandlebars` has a method not mirrored on `Handlebars`, it should be added.

**Comment by johnknoop** [comment]
This behaviour ought to be documented in the readme.
