### ISSUE TITLE
Question: How to properly write a DateTime formatting helper

### ISSUE THREAD

**Issue by cdokolas** [rexm/Handlebars.Net#207]
What would be the right way to write an, e.g. `fdate` helper to format a DateTime property?

I want to use something like `{{fdate myDate "HH:mm"}}` to pass `HH:mm` to `toString()`.

TIA

**Comment by cdokolas** [comment]
After some trial-and-error coding, I think this looks good enough:
``` c#
Handlebars.RegisterHelper("fdate", (writer, context, parameters) => {
    if (parameters.Length > 1)
        writer.WriteSafeString(((DateTime)parameters[0]).ToString(parameters[1] as string));
    else if (parameters.Length > 0)
        writer.WriteSafeString(((DateTime)parameters[0]).ToString());
});
```
Looks good to everyone?

**Comment by cdokolas** [comment]
Hit a snag when I misspelled the property:

How to properly test for `undefined` parameter? (i.e. when a property is not found)

The debugger shows something named "undefined" but I can't determine what it is.

**Comment by rexm** [comment]
It is an object of type `UndefinedBindingResult`, which is internal. Rather than checking for that specifically, I recommend you check for types you _can_ handle (`string`, `DateTime`, etc.)

**Comment by cdokolas** [comment]
For now, I'm checking that the `toString()` result is not an empty string, which is fine for `DateTime`s (they always produce some string). This will not suffice when the wrong property is passed (i.e. a non-`DateTime` object). I'm going to test the actual object type instead.

Couldn't there be something that is reliably testable (like `null` or something), just like javascript's `undefined`?

**Comment by rexm** [comment]
There's been requests to make `UndefinedBindingResult` a public type, we may do that in the future. For now, it seems there are a number of viable options at your disposal, including whitelist type checking, or TryParse on the stringified object.
