### ISSUE TITLE
Unregistered Helpers

### ISSUE THREAD

**Issue by BravoTango86** [rexm/Handlebars.Net#218]
Hi

With ThrowOnUnresolvedBindingExpression set to true, is it appropriate for a "Template references a helper that is not registered" exception to be thrown?

Else is it at all possible to add another option to the config to prevent all exceptions being thrown or accessible through a sanity checker?

Thanks a lot for a great bit of kit though - I'm planning to use this as part of a CMS and it should make life somewhat easier :-)

Cheers!

**Comment by rexm** [comment]
Suppressing all exceptions isn't something we'd probably want to support, but if there are specific kinds of exceptions that make sense to optionally suppress, PR always welcome!
