### ISSUE TITLE
Passing a model into a partial

### ISSUE THREAD

**Issue by leethomascook** [rexm/Handlebars.Net#22]
HI, Great job on this project - it's great. I have a pull request coming to turn this into a basic view engine.

One feature we are missing though, is the ability to pass a model into a partial like so:

```
<div class="carousel">
 <div class="carouse__swiper js-carousel" >
    {{#each Carousel.Slides}}
      <div class="carousel__item">
        {{#if Link}}
        <a class="carousel__link" href="{{Link.Url}}">
        {{/if}}
        
          {{>image Image}}
          <div class="title-inset">
            <h3 class="carousel__title">{{Title}}</h3>
            <p class="carousel__copy">{{Copy}}</p>
          </div>
        {{#if Link}}
        </a>
        {{/if}}
      </div>
    {{/each}}
  </div>
</div>
```

The Key bit being:    {{>image Image}} Where Image is the name of a model.

I noticed you added @root support, possible to add this as well?

Thanks,

Lee

**Comment by leethomascook** [comment]
After some playing around, it looks as though you automatically get passed the context of your loop, which is great and will cover 99% of scenarios, so you don't need to specify a model to pass in.

Would still be nice to have the choice though.

**Comment by rexm** [comment]
Is this how it works in the handlebarsjs library?

**Comment by leethomascook** [comment]
Yes.

**Comment by leethomascook** [comment]
Hi, I thought I would provide a use case for when this is a problem: 

We have an image partial that handles responsive images, so I don't have to keep repeating this markup.

Say I have a template that has two properties on my model that are images, called Image1 and image2.

I just want to pass the image object into my partial, otherwise how does the partial know which one to render.

Thanks,

Lee

**Comment by rexm** [comment]
Got it. PR is welcome if it's time sensitive, otherwise I don't have a timeframe yet for it.

**Comment by leethomascook** [comment]
Submitted a PR: https://github.com/rexm/Handlebars.Net/pull/23

Perhaps not the most elegant solution, but it works and I added a test.

**Comment by rexm** [comment]
OK, that's a start. I can add some detail about how the internals work to help steer: look at how the block helper accumulators work. They take all the word tokens that appear after the helper name, and accumulate those as a list of arguments to pass into the helper. That's important because a word argument could be resolved to a path expression, or a constant, or some other kind of expression that will ultimately be resolved to a value. We would want partials to work the same way.

**Comment by leethomascook** [comment]
Fair enough, I'll take a look this evening.

**Comment by xabikos** [comment]
Sorry to be not related but I see you are using the partial functionality on your example. Do we have to register these partials before using them. And if we have what is the configuration? I would expect a call like Handlebars.RegisterPartial(). Am I missing something?

**Comment by leethomascook** [comment]
Yes, you have to pre -register them. I do it like so, on app startup:

```
 public static void RegisterAllPartialViews()
        {
            ObjectFactory.Configure(x => x.AddRegistry<HandlebarsRegistry>());
            var fileService = ObjectFactory.GetInstance<IFileService>();

            string[] files = Directory.GetFiles(string.Format("{0}Views/", fileService.GetApplicationRoot()), "*.handlebars", SearchOption.AllDirectories);
            var handlebars = ObjectFactory.GetInstance<IHandlebars>();
            foreach (var file in files)
            {
                try
                {
                    var partialSource = File.ReadAllText(file);
                    var tempalteName = Path.GetFileNameWithoutExtension(file);
                    using (var reader = new StringReader(partialSource))
                    {
                        
                        var partialTemplate = handlebars.Compile(reader);
                        handlebars.RegisterTemplate(tempalteName, partialTemplate);
                    }

                }
                catch (Exception ex)
                {
                    throw new Exception(string.Format("There is a problem with the handlebars partial {0}",file ),ex);
                }
            }
        }

```

**Comment by xabikos** [comment]
@leethomascook  thank you very much for the answer. I think this should be more obvious in the documentation.

**Comment by maverickml7** [comment]
@leethomascook. Since your on this topic, It would be nice to get handlebars.net<http://handlebars.net> to handle the missing partials similar nustache. If the partials not there it simply carries on removing the {{>tag}}.

Forgive me if it is already there.

On Feb 6, 2015, at 5:46 AM, Charalampos Karypidis <notifications@github.com<mailto:notifications@github.com>> wrote:


@leethomascook<https://github.com/leethomascook> thank you very much for the answer. I think this should be more obvious in the documentation.

**Comment by rexm** [comment]
HandlebarsJS throws an exception if it encounters a missing partial; since this library is intended to be a port of HandlebarsJS to .NET, the same behavior was implemented here.

**Comment by rexm** [comment]
Had some time this morning; fixed with d4fa539c8bf361bbead3cc83ed243ff264088cd8

**Comment by rexm** [comment]
Updated NuGet 1.2.1

**Comment by rexm** [comment]
Minor clarification to @leethomascook and @xabikos regarding registering partials: it's not required to register partials before compile time; they only need to be registered when the template referencing them is actually executed.
