### ISSUE TITLE
Whitespace broke in 1.7.x and later?

### ISSUE THREAD

**Issue by kendallb** [rexm/Handlebars.Net#222]
We use Handlebars for rendering our email templates and it works great. We had been using 1.3.1 for a long time but I recently decided to update all our NuGet packages and updated Handlebars to 1.9.0 and found that two of our unit tests failed. I backed down to 1.6.8 and was able to get it to work, but it fails on anything later than 1.7.0 so the breakage appears to have happened there. 

We have some code in our test that renders the text version of an HTML template and it looks like this:

```
{{#CouponCodes}}
{{Code}} - {{Name}}{{/CouponCodes}}
```

When we feed it a list of coupon codes with Name and Code properties, it is supposed to render like this:

```
COUPON1 - Coupon One
COUPON2 - Coupon Two
```

Instead we get this, where the whitespace between the two lines is missing. The first line of whitespace appears to be there as it is just failing on the second coupon code, so the second coupon code does not get the newline from the template included like it should:

```
COUPON1 - Coupon OneCOUPON2 - Coupon Two
```

**Comment by rexm** [comment]
In fact it's the inverse - whitespace was broken until version 1.7.1. You are relying on a bug, where this library handled whitespace differently than the handlebars spec.

**Comment by kendallb** [comment]
Ok, I would be happy to change our templates to work correctly so we can move up. How should the Handlebars code be structured to get the result I am looking for, with each entry followed by a newline?

**Comment by rexm** [comment]
Use a newline escape sequence (\n)

**Comment by kendallb** [comment]
I thought the official handlebars spec honored spaces and newlines unless you used the ~ operators on the start or end of a variable to trim it? 

If \n works however I will use that as it will likely make our text templates a lot more readable. Getting the line spacing right at the same time as making it readable is not fun!

**Comment by rexm** [comment]
I've created a jsbin to illustrate the behavior in the handlebarsjs library, which this library attempts to match: http://jsbin.com/qelanas/1/edit?js,console

As you'll see in the first case, line breaks around the block helper tags are disregarded, but the explicit line break in the second is turned into a real line break in the output.

**Comment by kendallb** [comment]
Getting back to this after like 7 years (lol). Not sure if this has changed in 2.x and later (about to take a look) but in 1.7.1 and later trying to use the \n character does not work. So this:

{{#CouponCodes}}\n{{Code}} - {{Name}}{{/CouponCodes}}

Renders it all inline and the \n is ignored. But if I do that with the JS version it does work:

https://jsbin.com/mawobijuje/edit?js,console

That would be a suitable option for us, but the newline escape sequence is not working? Is it supposed to work?

**Comment by kendallb** [comment]
To be clear, for the above sequence I get the literal \n character back in the resulting text body. I suppose I could post process the text after I get it back to translate those, but I thought that would become a literal character subsitution like it is in the JS version? So I get this back:

```
\nCOUPON1 - Coupon One\nCOUPON2 - Coupon Two
```
