### ISSUE TITLE
Handlebars.RegisterTemplate single instance may cause unexpected problems

### ISSUE THREAD

**Issue by mikeprince3** [rexm/Handlebars.Net#223]
This one doesn't happen often, but I see it on occasion when running all of the unit tests. In PartialTests, the partial named "person" is defined a bunch. When Handlerbars.RegisterTemplate is called, it adds or updates (aka overwrites) the compiled partial in a static dictionary. 

During the tests, there seems to be a race condition where some tests are run in parallel and the partial is overwritten by another test before the previous test can render the template. This ends up showing the test as failed since the expected output doesn't match. Subsequent tests usually run fine so it's easy to chalk it up to an anomaly and move on. Note, I do not have the "Run Test in Parallel" toggle on in the Test Explorer.

I think this could potentially be an issue for sites with higher traffic and lots of templates since multiple areas of the site could potentially be calling RegisterTemplate with the same partial name for a variety of templates. This is the kind of bug that you might hear reports of from time to time but can never reproduce.

            string source = "Hello, {{>person}}!";

            var template = Handlebars.Compile(source);

            var data = new {
                name = "Marc"
            };

            Handlebars.RegisterTemplate("person", "{{name}}");            

            //now, elsewhere in the app on another thread someone calls this:
            Handlebars.RegisterTemplate("person", "{{yada}}");

            var result = template(data);

In the example above {{name}} will not exist in the partial so the result will be "Hello, !"

One simple solution is to use Handlebars.Create instead of Handlebars.Compile since it will use a fresh instance of the RegisteredTemplates dictionary.  Another simple approach could be to document this in the readme.md.  Anyone have any thoughts on this?

**Comment by rexm** [comment]
That's definitely why `Create` exists - if your requirements involve multiple contexts, you should have a separate Handlebars instance for each context. The static usages are just convenience shortcuts for the most typical case, where an application scope can safely assume a template with a given name is true and consistent across the entire app context for that template name.
