### ISSUE TITLE
"Sequence contains no elements" error for empty block helpers

### ISSUE THREAD

**Issue by drewbj21** [rexm/Handlebars.Net#224]
Hi,

I'm trying to do the following and get "Sequence contains no elements" error.

{{#if true}}{{else}}
It doesn't work!
{{/if}}

But it works fine when I do this:

{{#if true}}

{{else}}
It's not true.
{{/if}}

I'd prefer to not have to put an empty line in and it seems like it should still work that way. I've had this issue come up with other built-in helpers too. Has anyone else encountered this issue? Thanks in advance for the help!

**Comment by mikeprince3** [comment]
The #unless helper might be what you are looking for.

```
{{#unless true}}
It's not true.
{{/unless}}
```

http://handlebarsjs.com/builtin_helpers.html

**Comment by drewbj21** [comment]
Yes, that is definitely a better way to achieve the same thing but the problem is that some of our customers don't understand that...

I guess I'm wondering if the spacing issue I described above is something that needs to fixed. The spacing doesn't matter for similar logic in a language like C# so would this be a bug in handlebars?

**Comment by rexm** [comment]
Yes, it is a bug

**Comment by slahn** [comment]
I can't reproduce this with the newest version (1.9.3)

**Comment by rexm** [comment]
This is now fixed as of v1.9.3.
