### ISSUE TITLE
Any plan about adding support of 'block' and 'contentFor'?

### ISSUE THREAD

**Issue by Magentaize** [rexm/Handlebars.Net#225]
I noticed that express-hbs supports them by its built-in helps.

**Comment by rexm** [comment]
The main goal of this library is to maintain parity with the handlebarsjs library. Extra features and extensions are possible, but they need to fit within the ethos of "bringing handlebarsjs to c#".

**Comment by Magentaize** [comment]
Okey, thanks for your reply.
