### ISSUE TITLE
Cannot resolve expression and block helper with the same name

### ISSUE THREAD

**Issue by Magentaize** [rexm/Handlebars.Net#226]
Just like the source `{{#block_helper foo}}{{block_helper}}{{/block_helper}}` with a HandlebarsBlockHelper `block_helper`

**Comment by rexm** [comment]
Can you please elaborate? What is the repro case with code, expected outcome and actual outcome?

**Comment by Magentaize** [comment]
I use these code for test:
```csharp
            var source = "{{block_helper}}";
            Handlebars.RegisterHelper("block_helper", (writer, options, context, arguments) => {
            });
            var data = new
            {
                block_helper = "help string"
            };
            var template = Handlebars.Compile(source);
            var result = template(data);
```
The expected outcome should be "help string", but it throw a exception.
