### ISSUE TITLE
Passing Quote Literals

### ISSUE THREAD

**Issue by tonysneed** [rexm/Handlebars.Net#230]
When quotes are passed to a template, the are output encoded: &quot;

Is there a way to output quote literals?

**Comment by rexm** [comment]
Can you provide a repro case?

**Comment by tonysneed** [comment]
You bet. Here's my [repo](https://github.com/tonysneed/HelloHandleBars), where I am [passing](https://github.com/tonysneed/HelloHandleBars/blob/master/HelloHandleBars/Program.cs#L90) a string with quotes in it to a template.

```csharp
new Dictionary<string, object>
{
    { "ctor-class", "Person"},
    { "ctor-params", ""},
    { "ctor-content", @"Console.WriteLine(""ctor""); "},
},
```

The [template](https://github.com/tonysneed/HelloHandleBars/blob/master/HelloHandleBars/Templates/Partials/Constructors.hbs) looks like this:

```
public {{ctor-class}}({{ctor-params}})
{
    {{ctor-content}}
}
```

Running the program writes the following to the console:

```
public Person()
{
    Console.WriteLine(&quot;ctor&quot;);
}
```

**Comment by tonysneed** [comment]
P.S. I also notice that angle brackets are encoded as `&lt;` and `&gt;`.  Is there a way to turn the encoding off?

**Comment by rexm** [comment]
From the [handlebars documentation](http://handlebarsjs.com/):
>Handlebars HTML-escapes values returned by a {{expression}}. If you don't want Handlebars to escape a value, use the "triple-stash" `{{{`

So modifying your template to be:

    public {{ctor-class}}({{ctor-params}})
    {
        {{{ctor-content}}}
    }

Indicates to Handlebars that `ctor-content` contains data that is safe to pass through unescaped.
