### ISSUE TITLE
"Could not find helper " when block helper is used in partial

### ISSUE THREAD

**Issue by JonasMH** [rexm/Handlebars.Net#233]
When a block-helper is used in a partial the following exception is thrown:

```
HandlebarsDotNet.HandlebarsRuntimeException: 'Runtime error while rendering partial 'somePartial', see inner exception for more information'

Inner exception
HandlebarsRuntimeException: Template references a helper that is not registered. Could not find helper '#isEnum'
```

If the block-helper is used in the entry handlebars file/template it works as expected.

I have made a small repo that repreduces the bug https://github.com/JonasMH/HandlebarsNetBug

Also tested using Handlebars.js, where a comparable example works with a block helper in a template/partial.

Additional info:
Handlebars 1.9.0
Framework: Netcoreapp2.0

**Comment by Vetsoo** [comment]
Having the same issue.

**Comment by VoGu** [comment]
Hi JonashMH,

I've checked your code, and had to spend a considerable time on reading the source code of Handlebars.Net.
As far as I understand, you should register your helper before you register your partialview. 

**In more details:**

- **HandlebarsDotNet.Compiler.ExpressionBuilder. ConvertTokensToExpressions** method is called when a partial view registration is called.

- Then, in **HandlebarsDotNet.Compiler.HelperConverter**, it is checked that if a helper exists with given name.

Therefore, if you haven’t registered your helper yet, your statement is not converted into the BlockHelperExpression.

I’m not sure if this is something to fix, however, you can save your day by registering your helper before you register your partial.

Cheers!
VoGu

**Comment by JonasMH** [comment]
Great find @VoGu, thanks! It works as expected when the Helper is registered before the partial.

When thinking about it, it makes sense that helpers used in a partial should be registered beforehand. But, i do not see this anyway in the README or similar. When i have the time i will make a PR updating the readme to inform developers of the correct order.

I will leave the issue open, so the authors can decide if it should be fixed or it just the way it is meant to be. :)

**Comment by rexm** [comment]
No current plans to fix. A partial is the same as a whole template; in both cases they are compiled and a strong link is made between the compiled template and each helper it references, so it must be able to find the helper during compilation.
