### ISSUE TITLE
Is it possible to release a new version as we need @partial-block support

### ISSUE THREAD

**Issue by huysentruitw** [rexm/Handlebars.Net#235]

**Comment by jokin** [comment]
Inline support also has been added after the last release and would be included in a new release.

**Comment by huysentruitw** [comment]
I've just published a new NuGet package that was built from the current master (505ccf5e1bb6c0da2e32233db24197972eadc014 )

https://www.nuget.org/packages/CogniStreamer.Handlebars.Net/

**Comment by jokin** [comment]
Should be visible here: https://www.nuget.org/packages/Handlebars.Net/

I don't see it

**Comment by huysentruitw** [comment]
@jokin I'm not the official maintainer, so I had to publish under a different package name. The url to the package is in my previous comment. 👍

**Comment by mohd-akram** [comment]
@rexm Any chance of releasing a new version soon? :)

**Comment by rexm** [comment]
1.9.3 was released the other week that includes everything committed through April.
