### ISSUE TITLE
Add register partial example on README

### ISSUE THREAD

**Issue by xabikos** [rexm/Handlebars.Net#24]
Add an example of how to register partials on the README file

**Comment by rexm** [comment]
Send a PR and I'll happily accept it!

**Comment by xabikos** [comment]
PR is here. By the way is there another way to register partials except using the TextReader method?

**Comment by rexm** [comment]
Thanks. All HB templates (partials and others) are compiled down to a `Action<TextReader, object>` method, so that is currently the only way to register partials.
