### ISSUE TITLE
Feature request: option to turn off html escaping

### ISSUE THREAD

**Issue by gab** [rexm/Handlebars.Net#241]
Hi! I'm using your project for text formatting; I greatly enjoy the formatting flexibility on offer, but said text is destined to be displayed in GUI controls and saved in various places, but will never end up on a web page. Therefore it's a bit annoying that Handlebars.Net decides to html-escape everything (such as quotes to '&quot;').

I'm currently working around this by running WebUtility.HtmlDecode() on the output of Handlebars, but of course it's a waste of CPU power and could become problematic. It would be great if you added an option to toggle the escaping behavior.

Thanks!

**Comment by carlosjdelgado** [comment]
You can avoid escaping using triple brace: 

Example:

```
var data = new {
    title = "My new post",
    link = "<a href='www.github.com'>Go to github</a>";
};

var source =
@"<div class=""entry"">
  <h1>{{title}}</h1>
  <div class=""body"">
    {{link}}
  </div>
</div>";

var template = Handlebars.Compile(source);
var result = template(data);
/* result value:
<div class="entry">
  <h1>My New Post</h1>
  <div class="body">
    &lt;a href='www.github.com'&gt;Go to github&lt;/a&gt;
  </div>
</div>
*/

// Now with triple brace for link
source =
@"<div class=""entry"">
  <h1>{{title}}</h1>
  <div class=""body"">
    {{{link}}}
  </div>
</div>";
template = Handlebars.Compile(source);
result = template(data);
/* result value:
<div class="entry">
  <h1>My New Post</h1>
  <div class="body">
    <a href='www.github.com'>Go to github</a>
  </div>
</div>
*/
```

**Comment by gab** [comment]
Thanks Carlos for the info, I somehow had skimmed over that in the Handlebars documentation, or thought it wasn't implemented in Handlebars.NET.

**Comment by odannyc** [comment]
@rexm @carlosjdelgado 

Is there is an option to turn this off completely. I don't want to escape any of my text since I am not using Handlebars strictly in an HTML fashion. I'm using it to just add templating to text.
