### ISSUE TITLE
#if nested inside an #each

### ISSUE THREAD

**Issue by 1886** [rexm/Handlebars.Net#245]
I am finding that a nested "#if" if doesn't evaluate as true when it should if it sits inside an "#each"

EG the {{image}} always seems to be null

```
{{#each Links}}            
<li>
{{#if image}}<img src="{{image}}" />{{/if}}
<h3>{{title}}</h3>
</li>
{{/each}}
```

**Comment by jrlost** [comment]
Assuming image is a property of a link.  If so, you need to preface your object reference with a ```this.```

**Comment by 1886** [comment]
Yes image belongs to link. I tried this but it didn't work

`{{#if this.image}}<img src="{{this.image}}" />{{/if}}`

**Comment by jrlost** [comment]
What does your Links object look like?

**Comment by 1886** [comment]
Hi jrlost,

I managed to work around this by changing the way I deserialize my data.

I was storing links as JSON in my db and using JsonConvert.DeserializeObject(). I tried changing this to use JavaScriptSerializer and DeserializeObject() and it now works.

So I guess it is the way the object was being created.

Thanks for your help. Glad to get it sorted.
