### ISSUE TITLE
Accessing the parent context breaks when using block helpers

### ISSUE THREAD

**Issue by johan-gorter** [rexm/Handlebars.Net#246]
The code below does not work as expected, because accessing the parent context `../answer` produces `undefined` when I surround it with `{{#myBlock}}`. Without the `{{#myBlock}}` it works perfectly.

```cSharp
var runtime = Handlebars.Create();
runtime.RegisterHelper("myBlock", (writer, options, context, parameters) =>
{
    options.Template(writer, context);
});
var data = new Dictionary<string, object>
{
  {"answer", "42"},
  {"questions", new List<string> {"question1", "question2", "question3"} }
};
var template = runtime.Compile(@"
  {{#each questions}}
    {{#myBlock}}
      {{.}}={{../answer}}
    {{/myBlock}}
  {{/each}}
");

var output = template(data);
var expected = "\nquestion1=42\nquestion2=42\nquestion3=42\n";
Assert.Equal(expected, output.Replace(" ", ""));
```

I tried finding the bug myself, but I really need some help to understand where I should be looking.

Possible duplicate of #189

**Comment by rexm** [comment]
What is `#myblock` in your context?

**Comment by rexm** [comment]
The issue is with your pathing in the template. If you go up 2 levels (`../../answer`), it will work as expected. This is how the original Handlebars JS library handles it as well.

**Comment by johan-gorter** [comment]
Ok, this makes sense. My block helper was just doing something cosmetic, so I was not expecting it, but this is fine.
