### ISSUE TITLE
No way to have a backslash in front of a variable

### ISSUE THREAD

**Issue by slahn** [rexm/Handlebars.Net#247]
`Handlebars.Compile(@"\{{test}}")(new {test="X"})` returns `"{{test}}"`, which is obviously fine.
`Handlebars.Compile(@"\\{{test}}")(new {test="X"})` returns `"\{{test}}"`, which seems like a bug to me.

Handlebars.js handles them like I would expect, with the second rendering `"\X"` [jsfiddle](https://jsfiddle.net/Lcxob4cj/)

(discovered in [this question on SO](https://stackoverflow.com/questions/50121053/handlebars-net-with-local-file-path/50121175#50121175))

**Comment by rexm** [comment]
Released 1.9.3 to nuget including this fix.
