### ISSUE TITLE
Performance issue in rendering template

### ISSUE THREAD

**Issue by ManojAcharya-GEP** [rexm/Handlebars.Net#257]
Hi @rexm,

Greetings for the day!

I am facing performance issue while rendering a simple template using partials. Can you help me out please.

**Usecase**: I am trying to generate Elasticsearch JSON queries using Handlebar.Net templates. While these queries are storied in the file system in the form if Handlebar.Net templates which are read during runtime. The partial templates are registered first and then the main template is executed. The input payload contain the Json object which is passed to the Handlebar.Net template to generate the final output which are actual Elasticsearch JSON queries. _Note: The input JSON will always be dynamic._

**Problem**: While all my .Net code using Handlebars.Net APIs(except template()) as well as other codes executes pretty fast, the template() delegate has performance issues. For the simple template and input object, this line takes about 600milliseconds. My input JSON is in the form of JObject. **_And as suggested by you I am converting this object into ExpandoObject before passing it to the template delegate_.**

**Following is the .Net code sample:** (Each line of code has associated comment with its execution time)

```
public string GetQuery1(string mainTemplateName, JObject data)
{
    string mainTemplate = TemplateManager.Instance.GetMainTemplate(mainTemplateName); //0 ms
    Dictionary<string, string> partialTemplates = TemplateManager.Instance.GetPartialTemplate(mainTemplateName);//0 ms
    foreach (var partial in partialTemplates)   //Entire loop takes 26 ms
    {
        Handlebars.RegisterTemplate(partial.Key, partial.Value); 
    }
    var template = Handlebars.Compile(mainTemplate); //51 ms
    dynamic dataO = JsonConvert.DeserializeObject<ExpandoObject>(((JObject)data).ToString(), new ExpandoObjectConverter()); //0 ms
    string query = template(dataO); //600 ms
    return query;
}
```

**Main Template**:
```
{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "{{search_query}}",
            "fields": [
              {{#search_fields }}
              "{{.}}",
              {{/search_fields }}
            ],
            "default_operator": "{{default_operator}}"
          }
        }
      ],
      "filter":  
        {{>dac dac}}
    }
  }
}
```

**Dependent Partails**:

1. _dac_ -
```
 {{#if isTerms}}
   {{>terms}}
 {{/if}}
 {{#if isTerm}}
   {{>term}}
 {{/if}}
```
2. _term_ -
```
{
  "term": {
    "{{Field}}": {
      "value": "{{Value}}"
    }
  }
}
```
3. _terms_ -
```
{
  "terms": {
    "{{Field}}": [
      {{#each Value}}
      	"{{this}}"{{#unless @last}},{{/unless}}
      {{/each}}
    ]
  }
}
```

**Input Json**: (which is then converted to ExpandoObject)
```
{
 "search_query": "laptop",
 "search_fields": ["documentName", "documentCreator", "documentStatus"],
 "default_operator": "or",
 "dac": {
      "Field": "dM_Documents.isTemplate",
      "Value": "false",
      "isTerm": true
    }
}
```

Do you think I am missing anything here. 

**Note**: This is just a sample example. I have more complex usecase where I have to render the partial recursively which take more than 2 seconds to render the template.

**Comment by rexm** [comment]
The first time you execute the template after it's been compiled, it may be considerably slower because it is a brand-new assembly that's never been executed before. In the .NET world, that means things like JIT compilation are still in effect.

If you run the same line `template(dataO)` again right after the first, you should find that it takes between 15 and 25 milliseconds, and each subsequent run the same.

This is part of why the README strongly encourages users to cache templates for reuse once they've been compiled.

**Comment by ManojAcharya-GEP** [comment]
Hi @rexm,

Initially I though so. But that's not the case. I am getting the delay in each call. The 600ms delay for `template(dataO)` that I mentioned is an average for multiple runs.

Did you get a chance to run the code with the templates that I provided?

Thanks.

**Comment by rexm** [comment]
I reproduced your case and it performed as I described. Without more info I can’t help.

**Comment by rexm** [comment]
I don't use Visual Studio... this test looks unnecessarily complicated. What's with the factories and such? Please distill the test into a single Main.cs and I'll take a look.

**Comment by ManojAcharya-GEP** [comment]
Hi @rexm,

Good evening.

Apologies for making it complicated. Actually, I have been deeply into coding patterns, thus a simple test application written by me has all that. :)

Anyways, I have made it very simple this time. Please find the application zipped below.
[HandleBarsTestV2.zip](https://github.com/rexm/Handlebars.Net/files/2173098/HandleBarsTestV2.zip)

You can also find the executable file in the bin folder which you can run and see.

Thanks.

**Comment by rexm** [comment]
Reflecting over an Expando still takes time. [The README includes performance information about each kind of model type](https://github.com/rexm/Handlebars.Net#performance):

>Rendering starts to get slower (into the tens of milliseconds or more) on dynamic objects.

And that is what we see here - my tests are similar to yours, they show it takes about 80 milliseconds. The library is performing as documented - this is the cost of reflection in .NET.

If you want to avoid reflection costs, don't use a model that requires reflection. Dictionaries are extremely fast. One way is to use a custom JSON converter to deserialize your JSON object into a nested `Dictionary<string, object>` map. ([Example](https://gist.github.com/rexm/71136a09161ac8b0f66d1aee8b8d637d))

Using that method, I ran the test in <1ms. However, it still takes over 300ms to deserialize the input - so you may need to look at additional tuning there.

**Comment by ManojAcharya-GEP** [comment]
Hi @rexm,

Good Morning!

Thanks a ton for your help. Deserializing my JObject input to dictionary using your DictionaryConverter.cs class did the trick. Now my templates are rendering in 1 ms average.

Regarding the deserialization of my input to Dictionary, as you mentioned, it takes about 300 ms for the first call. But for all the subsequent calls it gets executed in no time. So we are good with it.

Thanks again.
