### ISSUE TITLE
Expose HandlebarsConfiguration for the current environment

### ISSUE THREAD

**Issue by xabikos** [rexm/Handlebars.Net#26]
For a project I am currently working on we are experiment on rendering Handlebars on the server side but be able to use the same templates with ember.js client side. Unfortunatelly when you want to render a partial in Ember you have to do it like this:
```c#
string source = @"<div id=""mainContainer"">
  {{mainContent}}
  <div id=""partialContainer"">
    {{partial 'name'}}  
  </div>
</div>";
```
This is not supported by the current implementation from my understanding. To be able to do this we have to register a helper. In order to achieve this we need access in the registered templates. I explored the code and I found out that this can achieved through HandlebarsConfiguration class. Even though this Class is exposed from IHandlebars interface I didn't find a way to access it. So my proposal is to add another property on Handlebars class like the snippet below:

```c#
public sealed partial class Handlebars {
  private static readonly IHandlebars _singleton = new HandlebarsEnvironment(new HandlebarsConfiguration());

  public static HandlebarsConfiguration Configuration {
    get { return _singleton.Configuration; }
  }
}
```

Is this a valid solution in order to send a PR?

And this is my code on how I register the helper
```c#
Handlebars.Handlebars.RegisterHelper("partial", (writer, context, parameters) =>
{
  var partialName = (string)parameters[0];
  var partialAction = Handlebars.Configuration.RegisteredTemplates.First(kvp => kvp.Key == partialName);.First(kvp => kvp.Key == partialName);
  partialAction.Value.Invoke(writer, context);
});
```
If it is a nice approach we could added on the README file as well.

**Comment by rexm** [comment]
Nice solution! Send it over :)

Regarding the readme, I'm starting to think it would be better to build out the wiki with stuff like this and keep the readme lean and kind of a barebones QuickStart guide. Thoughts?

**Comment by xabikos** [comment]
I completely agree on what you said. A nice wiki would make this awesome project even better. And some commenting on the code would help as well. I am trying to understand the big picture piece by piece. 

P.S By the way which is the usage of Create method in Handlebars class? Because it confuses me a bit.

**Comment by xabikos** [comment]
And as you can see in [Ember partials documentation](http://emberjs.com/guides/templates/rendering-with-helpers/) there are many more options to render a partial. Would you thing we could add this in the BuiltinHelpers class as with and if words or would you prefer to keep this repository only standard Handlebars and create another repository, e.g. Handlebars.net Ember?

**Comment by rexm** [comment]
It would probably be better to create a standalone suite of Ember-compatible extensions. I am not sure what you're asking regarding the Create method, though. Can you clarify?

**Comment by xabikos** [comment]
Ok then I will to create a different GitHub repository and maybe a corresponding Nuget package. The way that we can add the ember functionality is not so obvious so I would prefer to give an easier API for this.

Regarding the Create method I can't image a usage scenario. In which case and how it would used. But it's a minor issue in all cases.

**Comment by rexm** [comment]
Updated NuGet 1.2.2
