### ISSUE TITLE
Support for .NET 4.0 is broken since 1.9.3 ?

### ISSUE THREAD

**Issue by StefH** [rexm/Handlebars.Net#260]
The https://www.nuget.org/packages/Handlebars.Net/1.9.0 did only have `.NETFramework 4.0` as minimum requirement.

Since 1.9.3, this is move to `.NETFramework 4.5.2`.

Can you please lower the requirements again ?

**Comment by rexm** [comment]
That is the lowest version supported by Microsoft. We do not support versions that MS has dropped.
