### ISSUE TITLE
<script></script> within template

### ISSUE THREAD

**Issue by dpuddifoot** [rexm/Handlebars.Net#269]
Hi,

I am using Handlebars.Net to generate HTML pages, I need to set some JavaScript vars within the template, but noticed that any tokens within <script> tags are not replaced, e'g
<script>
            var test = {{name}}
</script> 

What would be the solution? I'm keen to keep the script in the templates rather then output via a helper.

Thanks

**Comment by rexm** [comment]
Handlebars treats the entire template as a string; it doesn’t have any notion of HTML JavaScript. Suggest you post the parts that are giving you trouble to see what’s wrong with them.
