### ISSUE TITLE
Inline templates not usable inside #each

### ISSUE THREAD

**Issue by lacutah** [rexm/Handlebars.Net#270]
{{#*inline \"item\"}}{{id}}{{/inline}}{{#each items}}{{>item}}{{/each}} 

will fail with exception due to not being able to find inline template "item". In the code, there were overridden context classes used by iterators that were not passing / providing the global inline templates dictionary making them available to the "each" context.

I wrote a fix and unit test for this issue. Although I used a light-touch, it may be a bit of a sledgehammer without my domain knowledge of this project, but appears to work. Pull request created.

**Comment by rexm** [comment]
#271 merged
