### ISSUE TITLE
Support for formatting placeholders

### ISSUE THREAD

**Issue by mrbelk** [rexm/Handlebars.Net#274]
Any thoughts towards providing string formatting in the placeholder like

```
{{Placeholder[,alignment][:formatString]}}
```

An actual example of this would be 
```
{{Quantity,7:F1}}
```
which would emit a numeric with one decimal place with spaces on the left to make a total width of 7.

**Comment by rexm** [comment]
Does handlebarsjs support this?

**Comment by mrbelk** [comment]
It doesn't, no, and I know your stated goal is to simply provide a "pure" .NET port of handlebarsjs and so you're probably disinclined to add this. But... there is another mustache/handlebars .Net port out there that does this and it's _very_ convenient because it removes the necessity of having to build out these helpers

**Comment by rexm** [comment]
Curious why not use that one if it does things outside the baseline that you need?

**Comment by rexm** [comment]
How would that work?

**Comment by jawn** [comment]
I don't know the internals of Handlebars.NET. There is no magic to support extensibility is there?

**Comment by vzwick** [comment]
@mrbelk where would one find that magical other library you're speaking of?

**Comment by akamyshanov** [comment]
@vzwick 
Just for reference, I believe the mentioned library is [mustache-sharp](https://github.com/jehugaleahsa/mustache-sharp).
And indeed, formatting support is very handy.
