### ISSUE TITLE
Partial view inside another partial view block

### ISSUE THREAD

**Issue by cokceken** [rexm/Handlebars.Net#280]
Hello,

I am trying to use partial views inside each other to create more flexibility. 

> view -> 
>     `{{#>branch}} {{>leaf}} {{/branch}}`
> branch -> 
>     `<div class="branch">{{>@partial-block }}</ div>`
> leaf -> 
>     `<div class="leaf">leaf</div>`

the result should be: `<div class="branch"><div class="leaf">leaf</div></ div>`
But the view does not compiling with the following error:
    InnerException: {"Code supposed to be unreachable"}
    Message: "An unhandled exception occurred while trying to compile the template"

**Comment by cokceken** [comment]
I discovered it is working using latest handlebars code, but not using the latest handlebars nuget package. Can you publish new nuget for the latest version?

**Comment by rexm** [comment]
Version 1.10.0 has been released to nuget.
