### ISSUE TITLE
Handlebars.Compile hangs permanently

### ISSUE THREAD

**Issue by Metalnem** [rexm/Handlebars.Net#283]
**Handlebars.Compile** hangs permanently when compiling some malformed inputs. Here is the full program to reproduce one such case:

```csharp
namespace Handlebars.Run
{
  public class Program
  {
    public static void Main(string[] args)
    {
      var text = "<p>{{>trbles=}\n ";
      HandlebarsDotNet.Handlebars.Compile(text);
    }
  }
}
```

Found via [SharpFuzz](https://github.com/Metalnem/sharpfuzz).

**Comment by vzwick** [comment]
Doesn't reproduce on 849d36ca4172c29943d7bd417edb3b24aeb6ebcc (i.e. current `master` branch).
