### ISSUE TITLE
How to prevent crosstalk between class libraries using Handlebars.Net independently

### ISSUE THREAD

**Issue by benuleau** [rexm/Handlebars.Net#287]
I have a few class libraries using Handlebars.Net in different fashions and I would like them to operate independently of one another; however, whenever I register a helper, partial, etc. in one library, it is accessible from the others as well. Is there any way to either keep the instances of Handlebars separated or clean up/dispose of the Handlebars.Net instance whenever I'm done with it in one class library?

**Comment by rexm** [comment]
Handlebars.Create() returns a new instance of Handlebars.

**Comment by benuleau** [comment]
Thanks!
