### ISSUE TITLE
Support ember bind to attribute syntax

### ISSUE THREAD

**Issue by xabikos** [rexm/Handlebars.Net#29]
I am trying to add support for binding to attribute syntax but it's hard to achieve it. A very simple example is the one below:

```c#
string source =@"<div {{bind-attr class='className'}}>{{title}}</div>";
var template = Handlebars.Handlebars.Compile(source);
var data = new {
  className = "foo",
  title = "My new post"
};
var result = template(data);
```

The main problem is that I am able to register a custom helper with the name "bind-attr" but then the arguments array has one element that is undefined. Do you think is feasible to achieve something like this with a custom helper or it needs more changes?

**Comment by rexm** [comment]
Interesting, how does the Handlebarsjs library handle that?

**Comment by rexm** [comment]
I set up a [JSBin test](http://jsbin.com/juyetifiqo/1/edit?js,console) and I see how the JS library handles it - it creates a hash structure that is passed in as an argument. Need to think about how this would translate over to the .NET version from a dev experience standpoint; and also currently the lexer cannot handle complex structures like `name=value`... that is a [TODO listed in the Tokenizer](https://github.com/rexm/Handlebars.Net/blob/master/source/Handlebars/Compiler/Lexer/Tokenizer.cs#L17).

**Comment by xabikos** [comment]
I think we can close this issue. After deeper investigation on Ember I found that the bind-attr will be removed from the code and from version 1.11, currently in beda, will support the standard way of binding to attributes, e.g. class="{{className}}". 

I saw also the TODO in the Tokenizer and by doing this I understood better this project. If I can help on further improvement please let me know.
