### ISSUE TITLE
#if doesn't work inside arrays?

### ISSUE THREAD

**Issue by leosdad** [rexm/Handlebars.Net#293]
Unfortunately Handlebars.Net doesn't seem to work correctly inside `@each` when retrieving values from an array. Consider the template below:
```handlebars
{{#each items}}
	<b>{{item.name}}:</b>
	{{#if item.description}}
		<p>Description: {{item.description}}</p>
	{{/if}}
	<br />
{{/each}}
```
With the data:
```javascript
var data = { 
    items: [
    	{
        item: {
          name: 'First item',
          description: 'This one has a description'
        }
      },
    	{
        item: {
          name: 'Second item'
          // This one has no description
        }
      }
    ]
};
```
In handlebars.js it works as expected (see http://jsfiddle.net/bkn4yLg7/3/):
```html
<b>First item:</b>
Description: This one has a description
<br />
<b>Second item:</b>
<br />
```
For Handlebars.Net I've used the following JSON and `NewtonSoft.Json.JsonConvert.DeserializeObject()`:
```json
{
  "items": [
    {
      "item": {
        "name": "First item",
        "description": "This one has a description"
      }
    },
    {
      "item": {
        "name": "Second item"
      }
    }
  ]
}
```
...but in the output is:
```html
<b>First item:</b>
<br />
<b>Second item:</b>
<br />
```
If anyone knows a solution, please help. Thanks.

_Originally posted by @leosdad in https://github.com/rexm/Handlebars.Net/issues/181#issuecomment-478255525_

**Comment by rexm** [comment]
Please see #181
