### ISSUE TITLE
Modulus in Handlebars.Net helper.

### ISSUE THREAD

**Issue by CodeCheetah** [rexm/Handlebars.Net#295]
Hi,

Is there a way to perform modulo operation with a helper similar to:
 
https://jaketrent.com/post/every-nth-item-in-handlebars-loop/

Any ideas?

Thanks

**Comment by rexm** [comment]
The logic in the example should be more or less portable to c#. Have you run into a specific problem?

**Comment by rexm** [comment]
Closed due to inactivity.
