### ISSUE TITLE
Space in expression results in error

### ISSUE THREAD

**Issue by nkwinder** [rexm/Handlebars.Net#30]
If there is a space inside an expression (e.g {{> partialName}} instead of {{>partialName}}) the binder crashes ("Reached unparseable token in expression"). 
Same happens when {{ property }} or {{# each mainmenu}} or {{# if isSelected}}

This is not happening in js library, so templates written for client side binding, might not work in server!

thanks

**Comment by rexm** [comment]
Version 1.2.5 handles whitespace correctly for `{{ path }}` and `{{ > partial }}`. More work needs to be done to handle `#` and `/`... probably need to separate out those characters from the WordParser and create a new BlockParser to distinguish between WordExpressionTokens and block tokens.

**Comment by rexm** [comment]
Updated NuGet 1.3.2
