### ISSUE TITLE
null value instead of an empty array not working

### ISSUE THREAD

**Issue by nkwinder** [rexm/Handlebars.Net#31]
if (for a model property) the value is null instead of an empty array, then #if and #each are not working the same way js library works. null doesn't seem to be recognized.

thanks

**Comment by rexm** [comment]
Need more info. Can you set up test cases to illustrate?

**Comment by nkwinder** [comment]
model:
"mainmenu":null

template:
{{#each mainmenu}}
	<li></li>
{{/each}}

with js library the above works. in server this raises "Object reference not set to an instance of an object"

**Comment by rexm** [comment]
I may eventually get to this... PR welcome in the meantime.

**Comment by rexm** [comment]
I can reproduce the `#each` failure you described, but `#if propertyThatIsNull` works correctly for me. Can you confirm?

**Comment by rexm** [comment]
Fix to `#each` in NuGet 1.2.6

**Comment by nkwinder** [comment]
My bad. `#if` works ok.
thanks for the quick fixes!!
