### ISSUE TITLE
Ampersands are rendered as &amp;

### ISSUE THREAD

**Issue by vkairys** [rexm/Handlebars.Net#318]
Ampersands are rendered as ```&amp;``` . For example 
```csharp
var source = "{{name}}";
var template = Handlebars.Compile(source);
var data = new
{
    name = "&"
};
var result = template(data); // result is &amp;
```

**Comment by rexm** [comment]
This is by design, Handlebars always escapes & encodes content by default. You can mark a block as "safe to render raw" by using three brackets instead of two, called "triple-stash" syntax: `{{{name}}}`
