### ISSUE TITLE
Update already Registered Partials

### ISSUE THREAD

**Issue by nkwinder** [rexm/Handlebars.Net#32]
That' s the same issue for which i had created this pull request. 
https://github.com/rexm/Handlebars.Net/pull/11

I though it was fixed, and i thought i had tested it, but it doesn't seem like it.

This is my code i requested to be merged:
https://github.com/rexm/Handlebars.Net/commit/f4798d73208dc176e5898afd1910e26320dd0c5c 

This is what was finally got merged:
https://github.com/rexm/Handlebars.Net/commit/42dc2dda0035144d460017839d397ac42f3722a1#diff-2924c3c1cf999a873ec9a22cec4ac706

So it's obvious why the update doesn't work. 

Any reason for this? 

Thank you

**Comment by rexm** [comment]
Weird, not sure how I missed that. Quick fix, I'll get it later this AM.

**Comment by rexm** [comment]
Updated NuGet 1.2.4
