### ISSUE TITLE
Example of blockhelper for iterator

### ISSUE THREAD

**Issue by statler** [rexm/Handlebars.Net#323]
Hi Rex

I am trying to build an iterator as a blockhelper that essentially just does
String.Join(",",MyValues);

Unfortunately, I can't seem to get it working - do you have an example of how the iterator is implemented - for example in the each case? I looked through the source, and couldn't really get my head around how to sort it out.

**Comment by rexm** [comment]
Can you share an example of how you’d want it to work? A template, data structure, and expected output showing the concept.

**Comment by statler** [comment]
Thanks for getting back to me Rex

Template

    {{#join "," lstPerson}}{{FullName}}{{/join}}

Class

    List<Person> lstPerson = new List<Person>(){new Person("Danny Devito"), new Person("Rodney Dangerfield", new Person("Henri Matisse")}};

Expected Output

    Danny Devito, Rodney Dangerfield, Henri Matisse

**Comment by rexm** [comment]
Something like this, needs better error handling but shows the idea:

```c#
Handlebars.RegisterHelper("join", (writer, options, context, arguments) => {
    //first arg is the delimiter
    var delimiter = (string)arguments[0];
    //second arg is the list
    var enumerable = (IEnumerable)arguments[1];
    //structure a loop so we check if there's another element before writing the delimiter
    var enumerator = enumerable.GetEnumerator();
    enumerator.MoveNext();
    while(true) {
        options.Template(writer, enumerator.Current);
        if(enumerator.MoveNext()) {
            writer.Write(delimiter);
        } else {
            break;
        }
    }
});
```

**Comment by statler** [comment]
Finally go time to get back to this. This works well, with just one issue...

I cannot seem to get the string value for the separator. arguments[0] is passed in as UndefinedBindingResult. I can see the value of the property, but arguments[0].ToString() is empty.

Any pointers on how to get that value?

**Comment by rexm** [comment]
Hm, not sure. What do you mean by "I can see the value of the property"?

**Comment by statler** [comment]
As in, in the debugger

![dbug](https://user-images.githubusercontent.com/337991/75292405-33681380-5878-11ea-9540-4ea6881f9ce2.png)

**Comment by statler** [comment]
It is definitely to do with the escaping. Because it is in an HTML document using an editor, the quotes are made 'safe'. I guess my only option is to parse it prior to templating with some form of regex to 'un-replace' the safe strings - yes?

**Comment by statler** [comment]
My mistake. In the end it was as simple as replacing the escaped quotes. Because the quotes were omitted, the templater read it as a property, not a literal.

        var joinregex = new Regex(@"({{#join.*?}})");
        inlineHTML = regex.Replace(inlineHTML, match => ReplaceEscapedJoinSeparator(match));

        public static string ReplaceEscapedJoinSeparator(Match Match)
        {            
            return Match.Value.Replace("&quot;","\"");
        }
