### ISSUE TITLE
Navigating an array by index doesn't work same as in handlebarsjs

### ISSUE THREAD

**Issue by johnrobertallan** [rexm/Handlebars.Net#33]
In javascript I can navigate an array using the following syntax

array.1.title

However I am yet to see this work in the .net library. Perhaps I have implemented something incorrectly but it seems straightforward. Any insight would be appreciated.

![handlebars-array-navigation](https://cloud.githubusercontent.com/assets/5693857/6177481/126f5b32-b2bc-11e4-8025-45e31ddc6a5a.png)

**Comment by rexm** [comment]
I missed this particular type of pathing... it'll need to be added.

**Comment by rexm** [comment]
This was fixed by @kll's PR #40 and included in the 1.2.10 NuGet release.
