### ISSUE TITLE
Literal cannot be used as property/index accessor

### ISSUE THREAD

**Issue by zjklee** [rexm/Handlebars.Net#331]
The following syntax is not correct for indexer accessor:
```csharp
var source = "{{#each names}}{{@root.names.[@index]}}{{/each}}"; 
var data = new 
{ 
      names = new[] { "Foo", "Bar" }
}; 
```
Expected result: `"FooBar"`
Actual result: `""`

As well as for property accessor:
```csharp
var source = "{{#each enumerateMe}}{{ @root.enumerateMe.[@key] }} {{/each}}"; 
var data = new 
{ 
        enumerateMe = new Dictionary<string, object> 
        { 
             { "foo", "hello" }, 
             { "bar", "world" } 
        } 
};
```
Expected result: `"hello world "`
Actual result: `"foo bar "`

I've found similar behaviour described in wycats/handlebars.js/pull/569

If mentioned behaviour is expected I'd like to volunteer to create a PR.

**Comment by rexm** [comment]
This pathing syntax isn't supported in Handlebars. In the thread on #569, the solution is to use a lookup helper, potentially in conjunction with sub-expressions.

**Comment by zjklee** [comment]
OK, probably I’ve missed something while reading the thread.
Bad to hear that this is an unsupported feature.
In case you would not accept the change - feel free to close the issue as well as the PR.

**Comment by alexb5dh** [comment]
Just wanted to confirm if there's still no built-in support for this?

**Comment by zjklee** [comment]
Hello @alexb5dh 
This can be achieved by using [lookup](https://handlebarsjs.com/guide/builtin-helpers.html#lookup) helper.
