### ISSUE TITLE
#each fails if property doesn't exist

### ISSUE THREAD

**Issue by johnrobertallan** [rexm/Handlebars.Net#34]
## Description

A template containing an #each block helper will fail if the property you are trying to iterate over does not exist. In HandlebarsJS the block is simply ignored.

## Temporary Solution

Wrap all your #each statements in an #if statement.

**Comment by johnrobertallan** [comment]
oh wait. this may have already been fixed, I will get the latest Nuget and confirm

**Comment by johnrobertallan** [comment]
yes. this is fixed now. sorry, i was still on 1.2.0

**Comment by rexm** [comment]
👍
