### ISSUE TITLE
'Handlebars statement was not reduced to a single expression' exceptions when invoking Handlebars.Compile reentrantly

### ISSUE THREAD

**Issue by perlun** [rexm/Handlebars.Net#357]
## Exception details

```
Unhandled exception. HandlebarsDotNet.HandlebarsCompilerException: Handlebars statement was not reduced to a single expression
   at HandlebarsDotNet.Compiler.ExpressionScopeConverter.ConvertTokens(IEnumerable`1 sequence)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HandlebarsDotNet.Compiler.ExpressionScopeConverter.Convert(IEnumerable`1 sequence)
   at HandlebarsDotNet.Compiler.ExpressionBuilder.ConvertTokensToExpressions(IEnumerable`1 tokens)
   at HandlebarsDotNet.Compiler.HandlebarsCompiler.Compile(TextReader source)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(TextReader template)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template)
   at HandlebarsDotNet.Handlebars.Compile(String template)
   at SiteGenerator.ConsoleApp.Program.IncludeHelper(TextWriter writer, Object context, Object[] parameters) in /home/per/git/halleluja.nu/bin_src/SiteGenerator.ConsoleApp/Program.cs:line 51
   at lambda_method(Closure , TextWriter , Object )
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.<>c__DisplayClass7_0.<Compile>b__0(Object context)
   at SiteGenerator.ConsoleApp.Program.Main(String[] args) in /home/per/git/halleluja.nu/bin_src/SiteGenerator.ConsoleApp/Program.cs:line 32
Aborted
```

## Details & Introduction

I am looking to rewrite an existing site which uses [Jekyll](https://jekyllrb.com/) at the moment into something a bit more "imperative", with less convention-over-configuration and less dependencies on external frameworks, and more control into my own hands. (Yes, I know very well that I am reinventing the wheel. :slightly_smiling_face:)

I looked briefly at [EJS](https://ejs.co/) which is a templating library for JavaScript, which also comes with a command-line utility for rendering EJS templates (to HTML in my case). But I'm not really a JavaScript person by heart, so I ended up googling my way here, to Handlebars.Net.

One of the first things I will need to get my suite built is a simple `include` helper. Something like `{{include 'foo.hbs'}}`, which includes `foo.hbs` relative to the site source folder (`src/` in my case). I know the same thing could be achieved with partials, but I prefer something explicit and straight-to-the-point in this case. I want my templates to be extremely easy to understand, even when I haven't looked at them for a year or two. They are just a means to an end.

However, when I try this I run into the exception posted above. Here is the full source of my program. I assume this is because `Handlebars.Compile` uses some shared state and isn't really intended to be used in this way. What's the best/proper way to do something like this, with the current v1 codebase? I guess I can use `Handlebars.Create` and create separate instances, but I'd prefer the configuration (like currently registered helpers) to follow along to the child instances. Any ideas?

## Example program

```c#
using System;
using System.IO;
using HandlebarsDotNet;

namespace SiteGenerator.ConsoleApp
{
    public static class Program
    {
        private const string SourceDir = "src";

        public static void Main(string[] args)
        {
            if (args.Length != 1)
            {
                Environment.Exit(1);
            }

            string source = File.ReadAllText(args[0]);

            Handlebars.RegisterHelper("include", IncludeHelper);

            var template = Handlebars.Compile(source);

            var data = new {
                title = "My new post",
                body = "This is my first post!"
            };

            var result = template(data);

            Console.WriteLine(result);
        }

        private static void IncludeHelper(TextWriter writer, dynamic context, object[] parameters)
        {
            if (parameters.Length != 1)
            {
                throw new HandlebarsException("{{include}} helper must have exactly one argument");
            }

            if (!(parameters[0] is string fileName))
            {
                throw new HandlebarsException("{{include}} expected string parameter, not " + parameters[0].GetType().Name);
            }

            string templateSource = File.ReadAllText(Path.Join(SourceDir, fileName));

            var template = Handlebars.Compile(templateSource);
            var result = template(context);

            writer.Write(result);
        }
    }
}
```

**Comment by zjklee** [comment]
Can you please share the content of the templates your trying to compile? This could help finding the root cause.
In addition I’d recommend looking at [zjklee/Handlebars.CSharp](https://github.com/zjklee/Handlebars.CSharp) (maintained fork).

**Comment by perlun** [comment]
Thanks @zjklee, this helped me locate the problem. My `src/includes/footer.hbs` looked like this:

```handlebars
<footer class="site-footer">
  <div class="wrapper">
    <div class="footer-col-wrapper">
      <div class="footer-col footer-col-1">
        &copy; {{ 'now' | date: "%Y" }} {{ site.title }}
      </div>
    </div>
  </div>
</footer>
```

This is from an old Liquid template I have been using previously. The `{{ 'now' | date: "%Y" }}` is what caused the problem. When removing it, all worked fine. :+1: 

Thanks for the suggestion about your fork. I think I'll give @rexm some more time before deciding on which fork to go with. There seems to be nice plans in #294, let's see how & if they are realized.
