### ISSUE TITLE
Any way to use Swag in Handlebars.net?

### ISSUE THREAD

**Issue by PhilipDaniels** [rexm/Handlebars.Net#39]
Having just run into the (frankly amazing!) revelation that handlebars does not support an "if" statement other than testing for truthyness, (see here https://github.com/wycats/handlebars.js/issues/206) I was led to the swag library: https://github.com/elving/swag

Looking at the APIs for the two projects I don't see any way to use Swag in Handlebars.net? Before I reimplement Swag in .Net...do you have any suggestions?

**Comment by rexm** [comment]
It's certainly possible to port any or all of the Swag helpers to .NET. I don't understand how Swag helps with the issue you linked to, though.

**Comment by PhilipDaniels** [comment]
It would provide you with an IF statement that could be used to actually test conditionals other than Javascript truthiness. Among other things.

I am using your processor in my static site generator - https://github.com/PhilipDaniels/Lithogen - and I have a need for this. I will probably port some of AssembleIO's helpers as well. When I have finished I will send you a note and you can decide if you want to incorporate them into your project. It would be nice if you had a Handlebars.Helpers namespace with a bunch of pre-defined helpers which users could register.

**Comment by rexm** [comment]
PR is welcome. As long as we are able to preserve the intent of the project, which is to make hb templates easily executable in a native .NET process, adding ancillary helpers around the edges shouldn't interfere with that.
