### ISSUE TITLE
BlockHelpers require literal arguments to be strings?

### ISSUE THREAD

**Issue by PhilipDaniels** [rexm/Handlebars.Net#41]
I have defined myself a new block helper following your pattern in BuiltinHelpers.cs:

        public static void and(TextWriter writer, HelperOptions options, dynamic context, params object[] arguments)
        {
            var args = RequireTwoArguments<object, object>("and", arguments);

            if (Handlebars.HandlebarsUtils.IsTruthy(args.Item1) && Handlebars.HandlebarsUtils.IsTruthy(args.Item2))
                options.Template(writer, context);
            else
                options.Inverse(writer, context);
        }

and this usage works ok:

    {{#and "3" "3"}}
      <p>3 and 3 are both truthy</p>
    {{else}}
      <p>2 and 3 are NOT both truthy</p>
    {{/and}}

However, if we change one or both of the string arguments to ints it fails with "Reached unparseable token in expression".

    {{#and 3 3}}
      <p>3 and 3 are both truthy</p>
    {{else}}
      <p>2 and 3 are NOT both truthy</p>
    {{/and}}

Maybe related to #30 ?

I haven't tested many other combinations, but have noted that

    {{#and Title Title}}

works when Title is defined.

**Comment by rexm** [comment]
I don't think there's very good test coverage on parsing non-string literals. Possible we could've broken that in a past change.

**Comment by rexm** [comment]
To get you started, 873026b5eaf8e68eef02d2288962f7bc27299513 gets parsing of numeric literals barely working. I haven't tested decimals or negative numbers. Also, that is just the parsing, not the evaluation - so they will still get passed in to the helper as strings. If you want to take it further, looking at the changes in that commit is a good place to start.

**Comment by rexm** [comment]
Updated NuGet 1.2.10

**Comment by PhilipDaniels** [comment]
Leaving aside the type conversion problem for now, I'm afraid it is still broken. It seems very sensitive to whitespace - note that your test passes because it has a double space. Here are a few results:

    {{#and 3 4}}          - Reached unparseable token in expression
    {{#and 3  4}}         - Passes the strings "3" and "4"
    {{#and 3 4 }}         - Passes 1 argument, the string "3"
    {{#and 3    4 }}      - Passes the strings "3" and "4"
    {{#and    3    4 }}   - Passes the strings "3" and "4"

    {{#and 3 "4"}}        - Passes the strings "3" and "4\"" (note the extra double quote)
    {{#and 3 "4" }}       - Passes the strings "3" and "4\"" (note the extra double quote)
    {{#and 3    "4" }}    - Passes the strings "3" and "4"
    {{#and    3   "4" }}  - Passes the strings "3" and "4"

    {{#and "3" 4}}        - Passes the strings "3" and "4"
    {{#and "3" 4 }}       - Passes the strings "3" and "4"

**Comment by rexm** [comment]
Well, as I said, it's
>barely working
:)
PR always welcome.

**Comment by rexm** [comment]
Some incremental improvements to the parser along the way seems to have improved this situation greatly. I've added each scenario listed above as a new unit test and we're all green, so I'm closing this issue as resolved for now.
