### ISSUE TITLE
Template function thread safety

### ISSUE THREAD

**Issue by jacobcl** [rexm/Handlebars.Net#42]
Hi, this is more of a question than an issue:
Are the template functions returned by the IHandlebars.Compile method thread safe?
On my app startup, I want to compile and cache several template functions and re-use them for requests (with different model values) without having to compile them over and over again.  Is this a supported use case?
Thanks,
Jacob

**Comment by ondrejtomcik** [comment]
Hi Jacob.
You can create instance of handlebars with custom configuration.
Custom configuration contains:
* Dictionary of Block Helpers*
* Dictionary of Helpers*
** Dictionary of Registred Templates**
* Expression name resolver*

You can create instance of handlebars with custom configuration.
```cs
var configuration = new HandlebarsConfiguration { ExpressionNameResolver = new UpperCamelCaseExpressionNameResolver() };
var handlebars = Handlebars.Create(configuration);

// register helpers
handlebars.RegisterHelper(HandlebarsHelpers.ResourceHelperKey, HandlebarsHelpers.ResourceHelper);

// register templates
handlebars.RegisterTemplate(name, template);
```

Registration of templates, helpers move to your app startup.

Accessing your templates for rendering:
```cs
configuration.RegisteredTemplates.TryGetValue(name, out template);
```

And you have now your compiled template. :)

**Comment by rexm** [comment]
Each template is compiled to a (mostly) state-less function. Unless you are doing something like changing the definition of helper on one thread while executing templates that reference the helper on another, you should be thread-safe.

**Comment by rexm** [comment]
Assuming this answered your question, closing. Feel free to re-open if you still need help.
