### ISSUE TITLE
[Help] Expression evalution in custom helpers and block helpers

### ISSUE THREAD

**Issue by breenyoung** [rexm/Handlebars.Net#43]
Just wondering how I can pass in non literal properties into custom helpers and have them be evaluated against the current context and accessible in code.

`{{mycustomhelper Person.Address.City}}
`

`{{#mycustomblock Person.FirstName}}
Hello world
`{{/mycustomblock}}

I can only seem to pass literal string into my custom helpers (double quoted)

**Comment by rexm** [comment]
Without more detail, I don't understand what the issue is. I created a [test that mimics your examples](https://gist.github.com/rexm/e1a045b9f76a48de642e) exactly, and it works as expected.
