### ISSUE TITLE
Bad Handlebars namespace naming

### ISSUE THREAD

**Issue by alberto-chiesa** [rexm/Handlebars.Net#44]
Hi, thanks for the library: it's neat, fast, and small! Kudos!

Maybe I'm missing something, but: am I the only one having issues with the Handlebars namespace?

The [guidelines](https://msdn.microsoft.com/en-us/library/ms229026%28v=vs.110%29.aspx) about namespace naming state: "DO NOT use the same name for a namespace and a type in that namespace".

The "why" is that currently, if I try to use Handlebars from my code, I can't set a "using Handlebars" directive, because Handlebars.Compile(...) is going to give a bad reference, because the compiler is going to search the Handlebars NAMESPACE, and not the class.

IMO, this means that Handlebars namespace should be renamed something else (HandlebarsDotNet, maybe?), to keep the usage of the static Handlebars class methods.

In the test classes the problem is not present, because the class is going to be resovled first, given the tests live in a Handlebars.Test namespace. Out of there, you can't.

I can Resharper out the namespace for you and make a pull request. Would you be interested?

Either this, or I'm a complete noob and I'm completely missing the point. ;)

**Comment by rexm** [comment]
This question has come up a few times. It was a goof to let it go out without fixing the namespace, but once it went into the wild I decided not to change it since it would be a breaking change for everyone already using it.

It seems like we may be on the cusp of a larger swell in adoption though, so it may be best to eat it now and go ahead and change.

**Comment by alberto-chiesa** [comment]
IMO, if it stays as it is, the library is not going to get the traction it deserves: the provided examples can't be used as they are, because if you're not in the Handlebars namespace, there is no way you can reference Handlebars just by name.

It's not good marketing for an otherwise neat library.

Just my 2c.

**Comment by rexm** [comment]
Pushed 1.3.0 to NuGet
