### ISSUE TITLE
Case Insensitive Data Support?

### ISSUE THREAD

**Issue by bcanzanella** [rexm/Handlebars.Net#47]
Greetings!

Is it possible to ignore the case of the template model's properties? I know that's not something used in Mustache/Handlebars, but this would allow templates to be shared by objects with different casing conventions like PascalCased objects (C#) and camelCased objects (js).

```
// js
var data = {"name" : "World"};
```
```
// c#
var data = new { Name = "World" };

```

```
// ... then this could be used by js or c#!
 var template = "Hello, {{name}}!";
```

**Comment by rexm** [comment]
There is a facility for making camelCased templates usable with PascalCased data objects:

    Handlebars.Configuration.ExpressionNameResolver = new UpperCamelCaseExpressionNameResolver();

**Comment by bcanzanella** [comment]
This is perfect, thanks!

**Comment by andrewduan** [comment]
you can create your own IExpressionNameResolver, for example,  make it case insensitive.
but not sure if it will slowdown the renering performance.

**Comment by rexm** [comment]
This is obsolete; a later version made binding case-insensitive altogether.
