### ISSUE TITLE
Remove Whitespace and Newline when using blocks

### ISSUE THREAD

**Issue by danielmarbach** [rexm/Handlebars.Net#51]
This might be something not worth diving into but I noticed that when I do something like:

```
{{ #if hasMethodsRemoved }}
<h4>Methods Removed</h4>
<ul>
  {{ #methodsRemoved }}
  <li><code>{{ name }}</code></li>
  {{ /methodsRemoved }}
</ul>
{{ /if }}
```

The result is
```
<h4>Methods Removed</h4>
<ul>

  <li><code>Foo()</code></li>
  <li><code>Foo()</code></li>

</ul>
```

Would you be interested in a PR to remove that whitespace? If yes any pointers where to start?

**Comment by rexm** [comment]
How does the handlebarsjs library output this test case?

**Comment by danielmarbach** [comment]
To be frank I haven't even looked

**Comment by danielmarbach** [comment]
I checked. Original handle bars also leaves whitespace. See each template on http://tryhandlebarsjs.com/

**Comment by rexm** [comment]
Thanks for following up!

**Comment by rexm** [comment]
I opened a new enhancement issue (#52) that touches on this. The JS library does allow for removing whitespace around a statement, that is not currently supported in this library.
