### ISSUE TITLE
Support for whitespace control (~)

### ISSUE THREAD

**Issue by rexm** [rexm/Handlebars.Net#52]
See the Whitespace Control section in the [http://handlebarsjs.com/expressions.html](handlebarsjs documentation):

>Template whitespace may be omitted from either side of any mustache statement by adding a ~ character by the braces. When applied all whitespace on that side will be removed up to the first handlebars expression or non-whitespace character on that side.
```
{{#each nav ~}}
  <a href="{{url}}">
    {{~#if test}}
      {{~title}}
    {{~^~}}
      Empty
    {{~/if~}}
  </a>
{{~/each}}
```

**Comment by danielmarbach** [comment]
I cannot promise you anything but I might be able to help out. Can you add pointers to this issue where I should look for to get a headstart?

**Comment by rexm** [comment]
The parser/lexer analyzes the template character-by-character and creates a sequence of tokens. Those token objects can have any number of properties on them that describe them, so we could indicate on the token whether it's a white space-removing token. However, this situation is a little tricky because we assume from the start that all text in the template is a static string of text (in fact that's the type of token it creates, static) and it's essentially hard-coded into the resulting compiled function. So we'd need to be able to seek "around" the token to look for white space and remove it, but that kind of logic happens further down at the expression conversion layer, after we've already set our static strings...

Sounds like an interesting project!

**Comment by BenSwayne** [comment]
Hi Rex/Daniel,

If this requires a lot of reworking behind the scenes, why don't we implement a custom TextReader that removes white space from the template itself before the template even gets to the Handlebars.net parser/lexer?

Perhaps this goes against the idea of this library or academic best way of doing it, but I think it could be written in a half day without knowing too much about the underpinnings of this library.

Thoughts? Comments?

**Comment by rexm** [comment]
That could maybe be an extension that lives in another project and allow for a pluggable TextReader in this one. The intent of this core is to provide parity with the original handlebarsjs library.

**Comment by rexm** [comment]
FYI, I've implemented this in main, but the Travis build is failing for reasons still being investigated...

**Comment by rexm** [comment]
This is implemented and currently available in the 1.5.0-beta version on NuGet. @danielmarbach @BenSwayne if convenient for you to test this updated package and feedback here, it would be appreciated!

**Comment by rexm** [comment]
Now available in 1.4.2

**Comment by danielmarbach** [comment]
Amazing! Going to update my site soon. Thx again!

**Comment by BenSwayne** [comment]
Awesome @rexm! Sorry I didn't get a chance to test it in beta, but I will test within the next 10 days and  likely have it in production on a few websites right away if testing goes well.
