### ISSUE TITLE
Issue with README.md example (RegisterHelper)

### ISSUE THREAD

**Issue by jonagh** [rexm/Handlebars.Net#53]
In README.md under the Registering Helpers section we have:
`Handlebars.RegisterHelper("link_to", (writer, context, parameters) => {
  writer.WriteSafeString("<a href='" + context.url + "'>" + context.text + "</a>");
});`

This seems to cause an error:
`'System.IO.TextWriter' has no applicable method named 'WriteSafeString' but appears to have an extension method by that name. Extension methods cannot be dynamically dispatched. Consider casting the dynamic arguments or calling the extension method without the extension method syntax.`

I can remedy the situation simply by changing `writer.WriteSafeString(...)` to `HandlebarsExtensions.WriteSafeString(writer, ...)`.

Am I missing something or is this an error in the readme's code?

**Comment by rexm** [comment]
The code sample in README is over-simplified; the exception is correctly stating that extension methods can't be dynamically dispatched, and `context` is dynamic. The simplest thing is to cast dynamics to `object` (i.e., `(object)context.text`). I don't mind updating the README to reflect that if it's causing too much confusion.

**Comment by jonagh** [comment]
Not a big deal for me, just thought I would mention it.
Thanks for the fast response, and thanks for Handlebars.Net

**Comment by vandre** [comment]
Since the code difference would be minimal I think it would still make sense to update the readme.md with the changes needed for the example to compile. (Especially coming from a JS background).

Thanks for posting this jonagh
