### ISSUE TITLE
How to escape encoding html tags

### ISSUE THREAD

**Issue by zoranpro** [rexm/Handlebars.Net#55]
Hi,

I am having Object data which value contains `<br />`. When I invoke the template I got encoded characters. Is there a possibility to keep `<br />`?

```
                var template = Handlebars.Compile(text);
                var data = new {
                    Signature =  "Some text <br /> some text"
                };

                string result = template(data);
```
As a result i get this `&lt;br /&gt;`. I would like to get `<br />`

**Comment by rexm** [comment]
Use the triple-stash syntax:

    {{{signature}}#

**Comment by zoranpro** [comment]
That solved it. Thanks.
