### ISSUE TITLE
Handlebars.dll v 1.0.5615 not strongly signed

### ISSUE THREAD

**Issue by jss3426** [rexm/Handlebars.Net#59]
Hi,
Is there any plan to sign this assembly and if yes, what is the time line?

**Comment by rexm** [comment]
I usually remember to sign it when I push it to NuGet, but since that's not an automated part of the build, sometimes I forget. I'll make sure the next version is signed.

**Comment by rexm** [comment]
NuGet 1.3.5 now contains assembly version 1.0.0 that has been signed.

**Comment by rexm** [comment]
NuGet 1.3.5 now includes a signed assembly version 1.0.0
