### ISSUE TITLE
Replacement is not occured

### ISSUE THREAD

**Issue by dejx** [rexm/Handlebars.Net#60]
Hello,

I'm attaching the code sample below about the issue i'm experiencing
```
[TestMethod]
public void Handlebar_Test_3()
{
	var template =
		"{{#home}}Welcome Home{{/home}}{{^home}}Welcome to {{newCity}}{{/home}}";

	var data = new Dictionary<string,object>();
	data["newCity"] = "New York City";
	data["oldCity"] = "Los Angelos ";
	data["home"] = false;
			
	var compiler = Handlebars.Compile(template);
	var result = compiler.Invoke(data);
	Assert.AreEqual("Welcome to New York City", result);
}
```

The result is
```
   Expected:<Welcome to New York City>. Actual:<Welcome to >. 
```

**Comment by rexm** [comment]
I had to go back to the Handlebars and Mustache specs to try to understand this one, and I'm still having a bit of a hard time. The `#key` syntax denotes a "section", which is supposed to use the non-falsy value as the context for the inner block. But in this case the value is a boolean and the context inside the block is still actually the parent context. So I may need to look at the actual implementation to understand if there is some type checking going on, or something else.

**Comment by rexm** [comment]
Based on some further investigation, it looks like the JS library is indeed doing a very specific type check on the section key, and if the value is a boolean type it treats the section expression as an if-block instead of a with-block.

**Comment by rexm** [comment]
NuGet 1.4.3
