### ISSUE TITLE
Is it possible to cache the template?

### ISSUE THREAD

**Issue by Phatzor** [rexm/Handlebars.Net#64]
Hi,

I tried to run som speed tests on Handlebars.net and it seemed like the compilation of the template took a bit of time. Is there a good way to cache a template, so it doesn't need to be recompiled every time? I looked into just using standard caching but since it returns a function it doesn't seem to work.

**Comment by rexm** [comment]
The templates can be cached. I'm not sure what "standard caching" is, though I would expect most in-process caches would be able to store a function delegate just fine. What do you mean by "doesn't seem to work"? Does it get an exception, or something else?

**Comment by Phatzor** [comment]
I don't know why I had this issue earlier, but it seems like the MemoryCache object can handle it with no issue.
