### ISSUE TITLE
Support for Hash Arguments

### ISSUE THREAD

**Issue by freakingawesome** [rexm/Handlebars.Net#67]
According to the [Handlebars documentation](http://handlebarsjs.com/expressions.html#helpers):

> Handlebars helpers can also receive an optional sequence of key-value pairs as their final parameter (referred to as hash arguments in the documentation):
> `{{{link "See more..." href=story.url class="story"}}}`
> The keys in hash arguments must each be simple identifiers, and the values are Handlebars expressions. This means that values can be simple identifiers, paths, or Strings.

In the javascript version, this come across in the last parameter passed to the helper function.

I see several possible ways of handling this:

1. If hash args are present, append a value onto the `arguments` array inside the `HandlebarsHelper` delegate. This stays closer to the functionality that the Javascript version uses, though it means we've got to do custom checking and casting every time we want to use it.
2. Pass hash args in an object to the `HandlebarsHelper` delegate. This feels more idiomatic but we run into a collision with the `HandlebarsBlockHelper` delegate, which already has an `options` parameter with the unfortunately-named class of `HelperOptions` (which should more appropriately be named `BlockHelperOptions`, IMO)

**Comment by rexm** [comment]
What about passing it as a dictionary as the last `arguments` value?

**Comment by freakingawesome** [comment]
Right, that's what I'm getting at with Option 1 above. But we'd probably want to wrap it in another class to match Handlebars, which gives you an object like this `{ "hash": { ... }, "data": { ... } }`

**Comment by freakingawesome** [comment]
I've been noodling around in the parser in an attempt to implement hash arguments, so I can take a stab at fully implementing this if you're interested.

**Comment by rexm** [comment]
Go for it!

**Comment by freakingawesome** [comment]
Will do!

**Comment by rexm** [comment]
We got a lot closer to this via @amaclean's PR#93. In fact, it may just work - but there's no test coverage to verify. At most, it looks like we would just need an improved expression visitor that can bind a HashExpression to the arguments array of a helper expression.

**Comment by rexm** [comment]
I did some basic tests and confirmed #93 does indeed cover the helper scenario as well as the partial scenario. If you supply hash arguments to the end of a helper statement, as specified in the handlebarsjs docs, the last element in the `args` array will be a `Dictionary<string, object>` of the hash arguments.
