### ISSUE TITLE
ViewEngine fork

### ISSUE THREAD

**Issue by mcintyre321** [rexm/Handlebars.Net#71]
I've got a fork over at https://github.com/mcintyre321/Handlebars.Net where I've added an MVC ViewEngine. 

My plan is to render Ghost themes from ASP.NET without having to modify them e.g. the [Caspar theme](https://github.com/TryGhost/Casper). To that end, I've also had to 

- extend the engine to handle the Layout tag from [Express-HBS](https://github.com/barc/express-hbs)
- auto-discover partials

and, more controversially

- check the context.Value (after checking for `@root`on the context object) for  `@variables` as ghost uses code like `{{@blog.title}}`, so I can pass `new {blog = new { title = ...}, post = new { ... } }` to a view, and the blog variable will be picked up

I'd like your thoughts on whether you'd be happy to merge this in (and set up a nuget package for the view engine) or if I should fork.

**Comment by rexm** [comment]
I think it'd be great to add to the solution as a separate NuGet package. I always envisioned the `@`-notation to someday be extensible, so I don't think it's necessarily controversial on the face of it - all about the implementation :)

**Comment by mcintyre321** [comment]
My biggest worry is about conflicts with non-@ variables.

I have another question you might be able to help with. In [HandlebarsCompiler.cs](https://github.com/mcintyre321/Handlebars.Net/blob/3a618cd34272fbff916c1dbb50d0b4f4e2295196/source/Handlebars/Compiler/HandlebarsCompiler.cs#L58) I've implemented the layouts by rendering the inner 'body' template, then passing this into the parent layout as a new anonymous variable:

```
            return (tw, vm) =>
            {
                var sb = new StringBuilder();
                using (var innerWriter = new StringWriter(sb))
                {
                    compiledView(innerWriter, vm);
                }
                var inner = sb.ToString();
                var layoutVm = new {body = inner};
                compiledLayout(tw, layoutVm);
            };
```

So the 'vm' property is the viewmodel that gets passed in. The problem is that the `@` variables on vm aren't on the layoutVm, and it looks to me like property evaluation is done using reflection against a Type. As I can't merge the vm and layour

**Comment by mcintyre321** [comment]
Whoops, submitted too early, please see above comment!
