### ISSUE TITLE
Allow local instances of Handlebars

### ISSUE THREAD

**Issue by natemcmaster** [rexm/Handlebars.Net#73]
**Proposal:**

Instead of only allowing use through a singleton, also allow local instances of Handlebars.

The API could look exactly the same.

```c#
var handlebars = new HandlebarComplier();

handlebars.RegisterHelper("link_to", (writer, context, parameters) => {
  writer.WriteSafeString("<a href='" + context.url + "'>" + context.text + "</a>");
});

string source = @"Click here: {{link_to}}";

var template = handlebars.Compile(source);

var data = new {
    url = "https://github.com/rexm/handlebars.net",
    text = "Handlebars.Net"
};

var result = template(data);

```

**Justification**
If I were to create a library that used this project, but because Handlebars is a global instance, I cannot guarantee that `Handlebars.RegisterHelper` will not overlap with other helpers.

**Comment by rexm** [comment]
We already do allow creating instances, mirroring the JS library:
```c#
var myInstance = Handlebars.Create();

**Comment by natemcmaster** [comment]
Good to know.
