### ISSUE TITLE
Reflection performance enhancements

### ISSUE THREAD

**Issue by rexm** [rexm/Handlebars.Net#74]
Overall, template rendering time is good - usually in the 10-15ms range for templates and data models of average size and complexity. But we can improve...

Profiling shows almost all execution time is spent in the [PathBinder, more specifically the AccessMember routine](https://github.com/rexm/Handlebars.Net/blob/master/source/Handlebars/Compiler/Translation/Expression/PathBinder.cs#L138).

Should evaluate ways to improve performance in this routine.

**Comment by gretro** [comment]
Hey.

I started to work on it. I actually need the performance boost for a project I'm working on. Combined to a ViewEngine for MVC, a page I need rendered takes 2 sec, which is way too long.

I started implementing the Generic dictionary part with ExpressionTrees. I was thinking of building a cache of certain types of IDictionary<,> that are most used. I was thinking of IDictionary<string, string> and IDictionary<string, object>. Would you have other types you think are used really often?

If you have any other suggestion, I will take happily take them.

**Comment by rexm** [comment]
2 seconds is quite a long time. Have you profiled to show the most delay is indeed in this routine.

**Comment by gretro** [comment]
To be honest, I don't think I've dwelved that far in the handlebar dll. I just wanted confirmation at that point that it was Handlebars .Net. I decided to fix it on my own. The page was rendered using a Dictionary&lt;string, object&gt; containing a sub-dictionary containing a least 100 elements.

What leads me to think it's this method is that I saw an improvement on performance when I used a {{#with }} block inside the {{#each }} block. After I'm done refactoring, I will make sure I run some performance tests on especially big generic dictionaries and big objects.

**Comment by gretro** [comment]
Oh, and I started a Unit test project for the modifications I'm making. I hooked NUnit, FluentAssertion and Faker.

**Comment by rexm** [comment]
There is already a unit test project, why would we not want to add to it?

**Comment by gretro** [comment]
The existing test project is composed of integration tests which test the system as a whole. They also provide very good use cases for anyone who want to start using the library. However, the other test project is really just about unit tests. It needs to be marked "friend assembly" since most classes are internal.

It seems just easier to split them, but I don't feel strongly about this. If you really prefer only one test project, I can merge them in my fork, so it will already be done when I do a pull request.

**Comment by rexm** [comment]
The stats in #82 don't seem like a worthwhile net improvement. Performance improvements should start with profiling test scenarios.
