### ISSUE TITLE
Chained conditionals

### ISSUE THREAD

**Issue by delapohl** [rexm/Handlebars.Net#79]
Does Handlebars.net support chained conditionals (http://handlebarsjs.com/block_helpers.html)?

```
{{#if isActive}}
  <img src="star.gif" alt="Active">
{{else if isInactive}}
  <img src="cry.gif" alt="Inactive">
{{/if}}
```

**Comment by rexm** [comment]
This is not currently supported, but it would be pretty easy to add to the existing conditional block builder.

**Comment by rexm** [comment]
Updated NuGet to 1.6.1

**Comment by delapohl** [comment]
Cursory tests look great. Thanks -- really appreciate your work on this project.
