### ISSUE TITLE
Escaping \{ sequences?

### ISSUE THREAD

**Issue by breenyoung** [rexm/Handlebars.Net#80]
Hi all,

I actually have an instance in my html where i need the sequence of `\{`

The scenario is an IMG tag that has windows style path to an image and the filename happens to be a GUID enclosed in { }

`<img src="C:\myapp\bin\x86\Debug\{67753ea8-ee68-4258-a50d-d159db749da0}.jpg"/>`

Handlebars.net is getting confused by this and basically leaving me with this:

`<img src="C:\myapp\bin\x86\Debug67753ea8-ee68-4258-a50d-d159db749da0}.jpg"/>`

How can I get around this and get Handlebars not to try to parse this?

Thanks

**Comment by breenyoung** [comment]
Thanks @rexm !

**Comment by rexm** [comment]
Updated NuGet 1.4.5

**Comment by breenyoung** [comment]
Thanks again @rexm, just updated my code this afternoon and it works like a charm!
