### ISSUE TITLE
Registering Helper for toUpper

### ISSUE THREAD

**Issue by Aroco** [rexm/Handlebars.Net#83]
Hi everybody,

i already implemented some Helpers, which i need. I am used to c# but not experienced in Handlebars.

I want all Text as upper-text beween the {{xUpper}}  {{/xUpper}}, so i tried (of course this will not work):

  Handlebars.RegisterHelper("ToUpper", (writer, context, args) =>
            {
                writer.Write(context.ToUpper());
            });

My Example:

{{#each Items}}
    public class {{Name}}
    { 
       {{#each Columns}}  {{xUpper}}test{{/xUpper}} {{Name}}{{/each}}
    }
{{/each}}

Is that possible? If yes, it would be very nice if ou provide a small example.

Thanks a lot and greetings 
Andy.

**Comment by rexm** [comment]
Did you find a solution to this? It might be nice to share in case anyone comes across this issue later.

**Comment by Aroco** [comment]
Hi Rex,

you're right. Sorry for closing the issue instead of posting a workaround. Now i use the variable i want to upper as argument to the registered function.

{{#each Items}}
    public class {{Name}}
    { 
	
    Alle Spalten {{#each Columns}}  {{ToUpper Name}}{{/each}}
	
    }
{{/each}}

#region ToUpper
            Handlebars.RegisterHelper("ToUpper", (writer, context, args) =>
            {
                try
                {
                    writer.Write(args[0].ToString().ToUpper());
                }
                catch (Exception ex)
                {
                    writer.WriteSafeString("!Error" + ex.Message + " !");
                }
              
            });
#endregion


Well i have to admit, that i have problems with the handlebars.net.
Would be very nice if you could answer following questions:
1) Where can i see which handlebars can be compiled? Are all handlebars of http://handlebarsjs.com/ implemented?
2) Is it possible to add javascript functions to the handlebars.net dll?
3) I wrote some more complex helpers in c#. Should i send them to you?

Sorry if i am on the complete wrong way.

Thanks a lot Andy

**Comment by rexm** [comment]
1. This isn't how the library is designed. It is mostly stateless - i.e. you give it a template, it turns it into a function and gives you the function back. If you want to implement some kind of catalog or dictionary of functions, that's on you.

2. No, this is a pure .NET library. It doesn't have any concept of JavaScript.

3. Can you elaborate?

**Comment by Aroco** [comment]
Hi,

i will add some more helpers to my solution and send it to you.
I think i still not in the handlebars theme. Is it not the problem to implement helpers in c# but to understand the "thinking" of handlebars. 
Is it possible to add you in skype?

Thank a lot
Andy

**Comment by rexm** [comment]
Send me your Skype name in an email (rex@rexmorgan.net)
