### ISSUE TITLE
property of nullable type crashes when object is null

### ISSUE THREAD

**Issue by vgorobec** [rexm/Handlebars.Net#85]
I have nullable property object in my root element, when this object is not initialized I get a NullReference exception instead of empty string. How can null values be ignored without using if?
Example:
I have something like {{model.Settings.MyProperty}}
I get exception when Settings is null, model always is not null.
To avoid exception I can use:
{{#if model.Settings}}
    {{model.Settings.MySetting}}
{{/if}}
but it's not convinient always use helpers (if, with), I would like to have possibility write  {{model.Settings.MyProperty}} and get empty string when Settings is null, or maybe I already can ignore null values during template compilation?
My code where I compile template looks like following
 var compiledTemplate = Handlebars.Compile(_webTemplate).;
 return compiledTemplate(_model);

Thanks!

**Comment by rexm** [comment]
Looks like a pretty simple gap we overlooked.

**Comment by rexm** [comment]
Updated NuGet to version 1.4.8

**Comment by vgorobec** [comment]
Thanks! I used 1.4.4 version, updated with 1.4.8 and it works fine now.
