### ISSUE TITLE
Nuget package install error

### ISSUE THREAD

**Issue by MattEllison** [rexm/Handlebars.Net#86]
when I try and run *PM> install Handlebars.Net* I get the error message below...

Join-Path : Cannot bind argument to parameter 'Path' because it is null.At C:\***\packages\jQuery.2.1.4\tools\install.ps1:3 
char:14
+ . (Join-Path $toolsPath common.ps1)
+              ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

**Comment by rexm** [comment]
With that info I don't understand how this is directly related to Handlebars. There is no PowerShell install.ps1 or JQuery dependency involved in Handlebars...

**Comment by MattEllison** [comment]
my apologies, I will look at it some more. Perhaps something else is interfering here. I will advise once I resolve. Thank you for your quick response.

**Comment by rexm** [comment]
Haven't gotten any updates; closing for now.
