### ISSUE TITLE
best approach to cache templates

### ISSUE THREAD

**Issue by agnauck** [rexm/Handlebars.Net#87]
thanks for this great library.

What would be the bets approach to cache templates in a multi threaded environment.
I also need the ability to refresh the templates in the cache when they changed.

Can I use *RegisterTemplate*, and *RegisteredTemplates.TryGetValue*, or should I create some custom cache?
With the build in cache is it thread safe to remove and rea-dd a templates, or update them?

Thanks,
Alex

**Comment by rexm** [comment]
Yes, it is thread-safe to call RegisterTemplate and overwrite an existing template.

**Comment by agnauck** [comment]
great, thanks for your fast reply
