### ISSUE TITLE
arguments types in helpers, Json	

### ISSUE THREAD

**Issue by agnauck** [rexm/Handlebars.Net#88]
I gave a basic template like this:

```html
{{#people}}
    {{ifCond firstName 'Bob'}}
        <li><b>{{firstName}}, {{lastName}}</b></li>
    {{else}}
        <li>{{firstName}}, {{lastName}}</li>
    {{/ifCond}}
{{/people}}
```

a basic helper like this:
```cs
Handlebars.RegisterHelper("ifCond", (writer, options, context, arguments) => {
    if (arguments[0] == arguments[1])
    {
        options.Template(writer, (object)context);
    }
    else
    {
        options.Inverse(writer, (object)context);
    }
});
```

my data is coming over Newtonsoft JSON ans looks like this:
```json
{  
  "people":[  
     {  
        "firstName":"Tom",
        "lastName":"Smith"
     },
     {  
        "firstName":"Bon",
        "lastName":"Jones"
     }
  ]
}
```

Argument 1 is the Helper is always a JObject instead of a string.
If I hardcode the data and pass it as a dynamic object it works as expected.

Should I convert my JSON to dynamic object always? Are there build in helpers for that?

**Comment by rexm** [comment]
There is no built-in handling for JObjects, because we declined to take on a mandatory dependency to JSON.NET.

However, there are examples for using JSON.NET to produce a compatible object in the unit test project: https://github.com/rexm/Handlebars.Net/blob/master/source/Handlebars.Test/DynamicTests.cs

**Comment by agnauck** [comment]
thanks, this helped. I also forgot to cast the argument from object to string.
Now it works as expected.
