### ISSUE TITLE
Want a pr for a nancy view engine?

### ISSUE THREAD

**Issue by SimonCropp** [rexm/Handlebars.Net#94]

**Comment by rexm** [comment]
It would be preferable to maintain the viewengine itself as a separate project, to keep the core lean. A PR would be great for any changes that are needed to make the core work well with a viewengine. Happy to link to the engine project, as well!

**Comment by SimonCropp** [comment]
As in u want a different repro?

**Comment by rexm** [comment]
I'm open to either that or separate project in the same solution.

**Comment by SimonCropp** [comment]
i would prefer different project in the same repo. then split repo if there is need in the future.

is this ok?

**Comment by rexm** [comment]
Sure

**Comment by jkrall** [comment]
@rexm Did you ever come up with a nancy view engine for handlebars.net?  Would love to try it out, if you've got anything working there.

**Comment by rexm** [comment]
No Nancy implementation, but a step in the right direction for viewengine providers generally.

**Comment by jkrall** [comment]
Sorry, I meant to tag @SimonCropp ... any chance you came up with something?

**Comment by SimonCropp** [comment]
Sorry no, i dropped the ball

**Comment by jkrall** [comment]
FYI -- I got this working, in case anyone finds this and is looking for the same thing:
https://gist.github.com/jkrall/923590957bc0a8aa230d50b9e8647a75
